# Form implementation generated from reading ui file 'Payment.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PaymentWidget(object):
    def setupUi(self, PaymentWidget):
        PaymentWidget.setObjectName("PaymentWidget")
        PaymentWidget.resize(900, 600)
        PaymentWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 12px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit, QComboBox, QDateTimeEdit {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 8px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus, QDateTimeEdit:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 13px;\n"
"        padding: 8px 15px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSearch, QPushButton#btnLuu {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSearch:hover, QPushButton#btnLuu:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnThem {\n"
"        background-color: #10b981;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnThem:hover {\n"
"        background-color: #059669;\n"
"    }\n"
"    QPushButton#btnSua {\n"
"        background-color: #f59e0b;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSua:hover {\n"
"        background-color: #d97706;\n"
"    }\n"
"    QPushButton#btnXoa {\n"
"        background-color: #ef4444;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnXoa:hover {\n"
"        background-color: #dc2626;\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnHuy, QPushButton#btnXuatExcel {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnHuy:hover, QPushButton#btnXuatExcel:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 8px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(PaymentWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=PaymentWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=PaymentWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=PaymentWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutSearch = QtWidgets.QHBoxLayout()
        self.layoutSearch.setSpacing(6)
        self.layoutSearch.setObjectName("layoutSearch")
        self.txtSearch = QtWidgets.QLineEdit(parent=PaymentWidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.layoutSearch.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=PaymentWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.layoutSearch.addWidget(self.btnSearch)
        self.btnRefresh = QtWidgets.QPushButton(parent=PaymentWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutSearch.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutSearch)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutBody = QtWidgets.QHBoxLayout()
        self.layoutBody.setSpacing(15)
        self.layoutBody.setObjectName("layoutBody")
        self.grpPaymentForm = QtWidgets.QGroupBox(parent=PaymentWidget)
        self.grpPaymentForm.setMinimumSize(QtCore.QSize(320, 0))
        self.grpPaymentForm.setMaximumSize(QtCore.QSize(350, 16777215))
        self.grpPaymentForm.setObjectName("grpPaymentForm")
        self.verticalLayout_form = QtWidgets.QVBoxLayout(self.grpPaymentForm)
        self.verticalLayout_form.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_form.setSpacing(12)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.verticalLayout_order = QtWidgets.QVBoxLayout()
        self.verticalLayout_order.setSpacing(4)
        self.verticalLayout_order.setObjectName("verticalLayout_order")
        self.lblDonHang = QtWidgets.QLabel(parent=self.grpPaymentForm)
        self.lblDonHang.setObjectName("lblDonHang")
        self.verticalLayout_order.addWidget(self.lblDonHang)
        self.cbDonHang = QtWidgets.QComboBox(parent=self.grpPaymentForm)
        self.cbDonHang.setObjectName("cbDonHang")
        self.verticalLayout_order.addWidget(self.cbDonHang)
        self.verticalLayout_form.addLayout(self.verticalLayout_order)
        self.verticalLayout_time = QtWidgets.QVBoxLayout()
        self.verticalLayout_time.setSpacing(4)
        self.verticalLayout_time.setObjectName("verticalLayout_time")
        self.lblNgayThanhToan = QtWidgets.QLabel(parent=self.grpPaymentForm)
        self.lblNgayThanhToan.setObjectName("lblNgayThanhToan")
        self.verticalLayout_time.addWidget(self.lblNgayThanhToan)
        self.dateThanhToan = QtWidgets.QDateTimeEdit(parent=self.grpPaymentForm)
        self.dateThanhToan.setCalendarPopup(True)
        self.dateThanhToan.setObjectName("dateThanhToan")
        self.verticalLayout_time.addWidget(self.dateThanhToan)
        self.verticalLayout_form.addLayout(self.verticalLayout_time)
        self.verticalLayout_amount = QtWidgets.QVBoxLayout()
        self.verticalLayout_amount.setSpacing(4)
        self.verticalLayout_amount.setObjectName("verticalLayout_amount")
        self.lblSoTienThanhToan = QtWidgets.QLabel(parent=self.grpPaymentForm)
        self.lblSoTienThanhToan.setObjectName("lblSoTienThanhToan")
        self.verticalLayout_amount.addWidget(self.lblSoTienThanhToan)
        self.txtSoTien = QtWidgets.QLineEdit(parent=self.grpPaymentForm)
        self.txtSoTien.setObjectName("txtSoTien")
        self.verticalLayout_amount.addWidget(self.txtSoTien)
        self.verticalLayout_form.addLayout(self.verticalLayout_amount)
        self.verticalLayout_method = QtWidgets.QVBoxLayout()
        self.verticalLayout_method.setSpacing(4)
        self.verticalLayout_method.setObjectName("verticalLayout_method")
        self.lblPhuongThucThanhToan = QtWidgets.QLabel(parent=self.grpPaymentForm)
        self.lblPhuongThucThanhToan.setObjectName("lblPhuongThucThanhToan")
        self.verticalLayout_method.addWidget(self.lblPhuongThucThanhToan)
        self.cbPhuongThuc = QtWidgets.QComboBox(parent=self.grpPaymentForm)
        self.cbPhuongThuc.setObjectName("cbPhuongThuc")
        self.cbPhuongThuc.addItem("")
        self.cbPhuongThuc.addItem("")
        self.cbPhuongThuc.addItem("")
        self.verticalLayout_method.addWidget(self.cbPhuongThuc)
        self.verticalLayout_form.addLayout(self.verticalLayout_method)
        self.verticalLayout_status = QtWidgets.QVBoxLayout()
        self.verticalLayout_status.setSpacing(4)
        self.verticalLayout_status.setObjectName("verticalLayout_status")
        self.lblTrangThaiThanhToan = QtWidgets.QLabel(parent=self.grpPaymentForm)
        self.lblTrangThaiThanhToan.setObjectName("lblTrangThaiThanhToan")
        self.verticalLayout_status.addWidget(self.lblTrangThaiThanhToan)
        self.cbTrangThai = QtWidgets.QComboBox(parent=self.grpPaymentForm)
        self.cbTrangThai.setObjectName("cbTrangThai")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.verticalLayout_status.addWidget(self.cbTrangThai)
        self.verticalLayout_form.addLayout(self.verticalLayout_status)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_form.addItem(spacerItem1)
        self.layoutBody.addWidget(self.grpPaymentForm)
        self.tblPayment = QtWidgets.QTableWidget(parent=PaymentWidget)
        self.tblPayment.setObjectName("tblPayment")
        self.tblPayment.setColumnCount(6)
        self.tblPayment.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPayment.setHorizontalHeaderItem(5, item)
        self.layoutBody.addWidget(self.tblPayment)
        self.verticalLayout_main.addLayout(self.layoutBody)
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setSpacing(10)
        self.layoutActions.setObjectName("layoutActions")
        self.btnThem = QtWidgets.QPushButton(parent=PaymentWidget)
        self.btnThem.setObjectName("btnThem")
        self.layoutActions.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=PaymentWidget)
        self.btnSua.setObjectName("btnSua")
        self.layoutActions.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=PaymentWidget)
        self.btnXoa.setObjectName("btnXoa")
        self.layoutActions.addWidget(self.btnXoa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutActions.addItem(spacerItem2)
        self.btnLuu = QtWidgets.QPushButton(parent=PaymentWidget)
        self.btnLuu.setObjectName("btnLuu")
        self.layoutActions.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=PaymentWidget)
        self.btnHuy.setObjectName("btnHuy")
        self.layoutActions.addWidget(self.btnHuy)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=PaymentWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutActions)
        self.lblStatus = QtWidgets.QLabel(parent=PaymentWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(PaymentWidget)
        QtCore.QMetaObject.connectSlotsByName(PaymentWidget)

    def retranslateUi(self, PaymentWidget):
        _translate = QtCore.QCoreApplication.translate
        PaymentWidget.setWindowTitle(_translate("PaymentWidget", "Quản lý Thanh toán"))
        self.lblIconBadge.setText(_translate("PaymentWidget", "💳"))
        self.lblTitle.setText(_translate("PaymentWidget", "QUẢN LÝ THANH TOÁN (PAYMENTS)"))
        self.lblSubtitle.setText(_translate("PaymentWidget", "Theo dõi giao dịch, phương thức thanh toán và kiểm soát trạng thái thanh toán hóa đơn"))
        self.txtSearch.setPlaceholderText(_translate("PaymentWidget", "Tìm theo mã đơn, phương thức..."))
        self.btnSearch.setText(_translate("PaymentWidget", "🔍 Tìm kiếm"))
        self.btnRefresh.setText(_translate("PaymentWidget", "🔄 Làm mới"))
        self.grpPaymentForm.setTitle(_translate("PaymentWidget", "Thông tin Thanh toán"))
        self.lblDonHang.setText(_translate("PaymentWidget", "Mã Đơn Hàng:"))
        self.lblNgayThanhToan.setText(_translate("PaymentWidget", "Ngày thanh toán:"))
        self.lblSoTienThanhToan.setText(_translate("PaymentWidget", "Số tiền thanh toán (VND):"))
        self.lblPhuongThucThanhToan.setText(_translate("PaymentWidget", "Phương thức:"))
        self.cbPhuongThuc.setItemText(0, _translate("PaymentWidget", "Tiền mặt"))
        self.cbPhuongThuc.setItemText(1, _translate("PaymentWidget", "Chuyển khoản"))
        self.cbPhuongThuc.setItemText(2, _translate("PaymentWidget", "Ví điện tử"))
        self.lblTrangThaiThanhToan.setText(_translate("PaymentWidget", "Trạng thái:"))
        self.cbTrangThai.setItemText(0, _translate("PaymentWidget", "Đã thanh toán"))
        self.cbTrangThai.setItemText(1, _translate("PaymentWidget", "Chưa thanh toán"))
        self.cbTrangThai.setItemText(2, _translate("PaymentWidget", "Hoàn tiền"))
        item = self.tblPayment.horizontalHeaderItem(0)
        item.setText(_translate("PaymentWidget", "Mã Giao Dịch"))
        item = self.tblPayment.horizontalHeaderItem(1)
        item.setText(_translate("PaymentWidget", "Mã Đơn Hàng"))
        item = self.tblPayment.horizontalHeaderItem(2)
        item.setText(_translate("PaymentWidget", "Ngày Thanh Toán"))
        item = self.tblPayment.horizontalHeaderItem(3)
        item.setText(_translate("PaymentWidget", "Số Tiền (VND)"))
        item = self.tblPayment.horizontalHeaderItem(4)
        item.setText(_translate("PaymentWidget", "Phương Thức"))
        item = self.tblPayment.horizontalHeaderItem(5)
        item.setText(_translate("PaymentWidget", "Trạng Thái"))
        self.btnThem.setText(_translate("PaymentWidget", "➕ Thêm mới"))
        self.btnSua.setText(_translate("PaymentWidget", "✏️ Sửa đổi"))
        self.btnXoa.setText(_translate("PaymentWidget", "🗑️ Xóa bỏ"))
        self.btnLuu.setText(_translate("PaymentWidget", "💾 Lưu lại"))
        self.btnHuy.setText(_translate("PaymentWidget", "❌ Hủy bỏ"))
        self.btnXuatExcel.setText(_translate("PaymentWidget", "📥 Xuất Excel"))
        self.lblStatus.setText(_translate("PaymentWidget", "Trạng thái: Sẵn sàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PaymentWidget = QtWidgets.QWidget()
    ui = Ui_PaymentWidget()
    ui.setupUi(PaymentWidget)
    PaymentWidget.show()
    sys.exit(app.exec())
