# Form implementation generated from reading ui file 'Statistics.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StatisticsWidget(object):
    def setupUi(self, StatisticsWidget):
        StatisticsWidget.setObjectName("StatisticsWidget")
        StatisticsWidget.resize(1000, 650)
        StatisticsWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 10px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QFrame#cardRevenue, QFrame#cardOrders, QFrame#cardAvgValue {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"    }\n"
"    QFrame#cardRevenue { border-left: 4px solid #7c3aed; }\n"
"    QFrame#cardOrders { border-left: 4px solid #ec4899; }\n"
"    QFrame#cardAvgValue { border-left: 4px solid #fb923c; }\n"
"    QLabel.lblCardTitle {\n"
"        color: #64748b;\n"
"        font-size: 13px;\n"
"        font-weight: 500;\n"
"    }\n"
"    QLabel.lblCardValue {\n"
"        color: #7c3aed;\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QDateEdit {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 6px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QDateEdit:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 13px;\n"
"        padding: 8px 15px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnFilter {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnFilter:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnXuatExcel {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnXuatExcel:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 8px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QFrame#frameChart {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(StatisticsWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(12)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=StatisticsWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=StatisticsWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=StatisticsWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutFilters = QtWidgets.QHBoxLayout()
        self.layoutFilters.setSpacing(8)
        self.layoutFilters.setObjectName("layoutFilters")
        self.lblTuNgay = QtWidgets.QLabel(parent=StatisticsWidget)
        self.lblTuNgay.setObjectName("lblTuNgay")
        self.layoutFilters.addWidget(self.lblTuNgay)
        self.dateStart = QtWidgets.QDateEdit(parent=StatisticsWidget)
        self.dateStart.setCalendarPopup(True)
        self.dateStart.setObjectName("dateStart")
        self.layoutFilters.addWidget(self.dateStart)
        self.lblDenNgay = QtWidgets.QLabel(parent=StatisticsWidget)
        self.lblDenNgay.setObjectName("lblDenNgay")
        self.layoutFilters.addWidget(self.lblDenNgay)
        self.dateEnd = QtWidgets.QDateEdit(parent=StatisticsWidget)
        self.dateEnd.setCalendarPopup(True)
        self.dateEnd.setObjectName("dateEnd")
        self.layoutFilters.addWidget(self.dateEnd)
        self.btnFilter = QtWidgets.QPushButton(parent=StatisticsWidget)
        self.btnFilter.setObjectName("btnFilter")
        self.layoutFilters.addWidget(self.btnFilter)
        self.btnRefresh = QtWidgets.QPushButton(parent=StatisticsWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutFilters.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutFilters)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutSummaryCards = QtWidgets.QHBoxLayout()
        self.layoutSummaryCards.setSpacing(15)
        self.layoutSummaryCards.setObjectName("layoutSummaryCards")
        self.cardRevenue = QtWidgets.QFrame(parent=StatisticsWidget)
        self.cardRevenue.setObjectName("cardRevenue")
        self.verticalLayout_cardRev = QtWidgets.QVBoxLayout(self.cardRevenue)
        self.verticalLayout_cardRev.setContentsMargins(15, 12, 15, 12)
        self.verticalLayout_cardRev.setSpacing(5)
        self.verticalLayout_cardRev.setObjectName("verticalLayout_cardRev")
        self.lblCardRevTitle = QtWidgets.QLabel(parent=self.cardRevenue)
        self.lblCardRevTitle.setObjectName("lblCardRevTitle")
        self.verticalLayout_cardRev.addWidget(self.lblCardRevTitle)
        self.lblTotalRevenue = QtWidgets.QLabel(parent=self.cardRevenue)
        self.lblTotalRevenue.setObjectName("lblTotalRevenue")
        self.verticalLayout_cardRev.addWidget(self.lblTotalRevenue)
        self.layoutSummaryCards.addWidget(self.cardRevenue)
        self.cardOrders = QtWidgets.QFrame(parent=StatisticsWidget)
        self.cardOrders.setObjectName("cardOrders")
        self.verticalLayout_cardOrd = QtWidgets.QVBoxLayout(self.cardOrders)
        self.verticalLayout_cardOrd.setContentsMargins(15, 12, 15, 12)
        self.verticalLayout_cardOrd.setSpacing(5)
        self.verticalLayout_cardOrd.setObjectName("verticalLayout_cardOrd")
        self.lblCardOrdTitle = QtWidgets.QLabel(parent=self.cardOrders)
        self.lblCardOrdTitle.setObjectName("lblCardOrdTitle")
        self.verticalLayout_cardOrd.addWidget(self.lblCardOrdTitle)
        self.lblTotalOrders = QtWidgets.QLabel(parent=self.cardOrders)
        self.lblTotalOrders.setObjectName("lblTotalOrders")
        self.verticalLayout_cardOrd.addWidget(self.lblTotalOrders)
        self.layoutSummaryCards.addWidget(self.cardOrders)
        self.cardAvgValue = QtWidgets.QFrame(parent=StatisticsWidget)
        self.cardAvgValue.setObjectName("cardAvgValue")
        self.verticalLayout_cardAvg = QtWidgets.QVBoxLayout(self.cardAvgValue)
        self.verticalLayout_cardAvg.setContentsMargins(15, 12, 15, 12)
        self.verticalLayout_cardAvg.setSpacing(5)
        self.verticalLayout_cardAvg.setObjectName("verticalLayout_cardAvg")
        self.lblCardAvgTitle = QtWidgets.QLabel(parent=self.cardAvgValue)
        self.lblCardAvgTitle.setObjectName("lblCardAvgTitle")
        self.verticalLayout_cardAvg.addWidget(self.lblCardAvgTitle)
        self.lblAvgOrderValue = QtWidgets.QLabel(parent=self.cardAvgValue)
        self.lblAvgOrderValue.setObjectName("lblAvgOrderValue")
        self.verticalLayout_cardAvg.addWidget(self.lblAvgOrderValue)
        self.layoutSummaryCards.addWidget(self.cardAvgValue)
        self.verticalLayout_main.addLayout(self.layoutSummaryCards)
        self.layoutReports = QtWidgets.QHBoxLayout()
        self.layoutReports.setSpacing(15)
        self.layoutReports.setObjectName("layoutReports")
        self.verticalLayout_table = QtWidgets.QVBoxLayout()
        self.verticalLayout_table.setSpacing(5)
        self.verticalLayout_table.setObjectName("verticalLayout_table")
        self.lblTableTitle = QtWidgets.QLabel(parent=StatisticsWidget)
        self.lblTableTitle.setStyleSheet("font-weight: bold; color: #334155; font-size: 13px;")
        self.lblTableTitle.setObjectName("lblTableTitle")
        self.verticalLayout_table.addWidget(self.lblTableTitle)
        self.tblStatistics = QtWidgets.QTableWidget(parent=StatisticsWidget)
        self.tblStatistics.setObjectName("tblStatistics")
        self.tblStatistics.setColumnCount(6)
        self.tblStatistics.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblStatistics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStatistics.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStatistics.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStatistics.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStatistics.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblStatistics.setHorizontalHeaderItem(5, item)
        self.verticalLayout_table.addWidget(self.tblStatistics)
        self.layoutReports.addLayout(self.verticalLayout_table)
        self.verticalLayout_chart = QtWidgets.QVBoxLayout()
        self.verticalLayout_chart.setSpacing(5)
        self.verticalLayout_chart.setObjectName("verticalLayout_chart")
        self.lblChartTitle = QtWidgets.QLabel(parent=StatisticsWidget)
        self.lblChartTitle.setStyleSheet("font-weight: bold; color: #334155; font-size: 13px;")
        self.lblChartTitle.setObjectName("lblChartTitle")
        self.verticalLayout_chart.addWidget(self.lblChartTitle)
        self.frameChart = QtWidgets.QFrame(parent=StatisticsWidget)
        self.frameChart.setMinimumSize(QtCore.QSize(400, 0))
        self.frameChart.setObjectName("frameChart")
        self.verticalLayout_innerChart = QtWidgets.QVBoxLayout(self.frameChart)
        self.verticalLayout_innerChart.setObjectName("verticalLayout_innerChart")
        self.lblChartPlaceholder = QtWidgets.QLabel(parent=self.frameChart)
        self.lblChartPlaceholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblChartPlaceholder.setStyleSheet("color: #94a3b8; font-style: italic; font-size: 12px;")
        self.lblChartPlaceholder.setObjectName("lblChartPlaceholder")
        self.verticalLayout_innerChart.addWidget(self.lblChartPlaceholder)
        self.verticalLayout_chart.addWidget(self.frameChart)
        self.layoutReports.addLayout(self.verticalLayout_chart)
        self.verticalLayout_main.addLayout(self.layoutReports)
        self.layoutFooterActions = QtWidgets.QHBoxLayout()
        self.layoutFooterActions.setObjectName("layoutFooterActions")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutFooterActions.addItem(spacerItem1)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=StatisticsWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutFooterActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutFooterActions)
        self.lblStatus = QtWidgets.QLabel(parent=StatisticsWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(StatisticsWidget)
        QtCore.QMetaObject.connectSlotsByName(StatisticsWidget)

    def retranslateUi(self, StatisticsWidget):
        _translate = QtCore.QCoreApplication.translate
        StatisticsWidget.setWindowTitle(_translate("StatisticsWidget", "Báo cáo Thống kê doanh thu"))
        self.lblIconBadge.setText(_translate("StatisticsWidget", "📈"))
        self.lblTitle.setText(_translate("StatisticsWidget", "THỐNG KÊ DOANH THU & ĐƠN HÀNG (STATISTICS)"))
        self.lblSubtitle.setText(_translate("StatisticsWidget", "Báo cáo doanh số livestream bán hàng, số hóa đơn tạo, và giá trị giao dịch trung bình theo thời gian"))
        self.lblTuNgay.setText(_translate("StatisticsWidget", "Từ ngày:"))
        self.lblDenNgay.setText(_translate("StatisticsWidget", "Đến:"))
        self.btnFilter.setText(_translate("StatisticsWidget", "🔍 Lọc báo cáo"))
        self.btnRefresh.setText(_translate("StatisticsWidget", "🔄 Làm mới"))
        self.lblCardRevTitle.setText(_translate("StatisticsWidget", "💰 TỔNG DOANH THU"))
        self.lblCardRevTitle.setProperty("class", _translate("StatisticsWidget", "lblCardTitle"))
        self.lblTotalRevenue.setText(_translate("StatisticsWidget", "0 VNĐ"))
        self.lblTotalRevenue.setProperty("class", _translate("StatisticsWidget", "lblCardValue"))
        self.lblCardOrdTitle.setText(_translate("StatisticsWidget", "📦 TỔNG ĐƠN ĐẶT HÀNG"))
        self.lblCardOrdTitle.setProperty("class", _translate("StatisticsWidget", "lblCardTitle"))
        self.lblTotalOrders.setText(_translate("StatisticsWidget", "0 đơn đặt"))
        self.lblTotalOrders.setProperty("class", _translate("StatisticsWidget", "lblCardValue"))
        self.lblCardAvgTitle.setText(_translate("StatisticsWidget", "📈 GIÁ TRỊ ĐƠN TRUNG BÌNH"))
        self.lblCardAvgTitle.setProperty("class", _translate("StatisticsWidget", "lblCardTitle"))
        self.lblAvgOrderValue.setText(_translate("StatisticsWidget", "0 VNĐ"))
        self.lblAvgOrderValue.setProperty("class", _translate("StatisticsWidget", "lblCardValue"))
        self.lblTableTitle.setText(_translate("StatisticsWidget", "Doanh thu chi tiết theo từng Livestream"))
        item = self.tblStatistics.horizontalHeaderItem(0)
        item.setText(_translate("StatisticsWidget", "Mã Stream"))
        item = self.tblStatistics.horizontalHeaderItem(1)
        item.setText(_translate("StatisticsWidget", "Tiêu Đề Livestream"))
        item = self.tblStatistics.horizontalHeaderItem(2)
        item.setText(_translate("StatisticsWidget", "Người Bán"))
        item = self.tblStatistics.horizontalHeaderItem(3)
        item.setText(_translate("StatisticsWidget", "Doanh Thu (VND)"))
        item = self.tblStatistics.horizontalHeaderItem(4)
        item.setText(_translate("StatisticsWidget", "Số Đơn Đặt"))
        item = self.tblStatistics.horizontalHeaderItem(5)
        item.setText(_translate("StatisticsWidget", "Sản Phẩm Đã Bán"))
        self.lblChartTitle.setText(_translate("StatisticsWidget", "Biểu đồ trực quan hóa doanh số"))
        self.lblChartPlaceholder.setText(_translate("StatisticsWidget", "[ Biểu đồ thống kê hình cột & hình tròn sẽ được hiển thị khi chạy ứng dụng ]"))
        self.btnXuatExcel.setText(_translate("StatisticsWidget", "📈 Xuất Báo Cáo Excel"))
        self.lblStatus.setText(_translate("StatisticsWidget", "Trạng thái: Đã tải báo cáo mới nhất"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StatisticsWidget = QtWidgets.QWidget()
    ui = Ui_StatisticsWidget()
    ui.setupUi(StatisticsWidget)
    StatisticsWidget.show()
    sys.exit(app.exec())
