# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(650, 520)
        LoginDialog.setMinimumSize(QtCore.QSize(650, 520))
        LoginDialog.setMaximumSize(QtCore.QSize(650, 520))
        LoginDialog.setStyleSheet("\n"
"    QDialog {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"            stop:0 #6d28d9, stop:0.35 #a855f7, stop:0.7 #ec4899, stop:1 #fb923c);\n"
"    }\n"
"   ")
        self.blobTopLeft = QtWidgets.QFrame(parent=LoginDialog)
        self.blobTopLeft.setGeometry(QtCore.QRect(-70, -70, 220, 220))
        self.blobTopLeft.setStyleSheet("\n"
"     #blobTopLeft {\n"
"         background-color: rgba(255, 255, 255, 40);\n"
"         border-radius: 110px;\n"
"     }\n"
"    ")
        self.blobTopLeft.setObjectName("blobTopLeft")
        self.blobBottomRight = QtWidgets.QFrame(parent=LoginDialog)
        self.blobBottomRight.setGeometry(QtCore.QRect(480, 360, 240, 240))
        self.blobBottomRight.setStyleSheet("\n"
"     #blobBottomRight {\n"
"         background-color: rgba(255, 255, 255, 35);\n"
"         border-radius: 120px;\n"
"     }\n"
"    ")
        self.blobBottomRight.setObjectName("blobBottomRight")
        self.blobAccentGold = QtWidgets.QFrame(parent=LoginDialog)
        self.blobAccentGold.setGeometry(QtCore.QRect(540, 30, 110, 110))
        self.blobAccentGold.setStyleSheet("\n"
"     #blobAccentGold {\n"
"         background-color: rgba(253, 224, 71, 90);\n"
"         border-radius: 55px;\n"
"     }\n"
"    ")
        self.blobAccentGold.setObjectName("blobAccentGold")
        self.blobAccentCyan = QtWidgets.QFrame(parent=LoginDialog)
        self.blobAccentCyan.setGeometry(QtCore.QRect(-30, 330, 90, 90))
        self.blobAccentCyan.setStyleSheet("\n"
"     #blobAccentCyan {\n"
"         background-color: rgba(34, 211, 238, 90);\n"
"         border-radius: 45px;\n"
"     }\n"
"    ")
        self.blobAccentCyan.setObjectName("blobAccentCyan")
        self.lblDecoSparkle1 = QtWidgets.QLabel(parent=LoginDialog)
        self.lblDecoSparkle1.setGeometry(QtCore.QRect(50, 55, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblDecoSparkle1.setFont(font)
        self.lblDecoSparkle1.setObjectName("lblDecoSparkle1")
        self.lblDecoConfetti = QtWidgets.QLabel(parent=LoginDialog)
        self.lblDecoConfetti.setGeometry(QtCore.QRect(560, 90, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblDecoConfetti.setFont(font)
        self.lblDecoConfetti.setObjectName("lblDecoConfetti")
        self.lblDecoStar = QtWidgets.QLabel(parent=LoginDialog)
        self.lblDecoStar.setGeometry(QtCore.QRect(40, 410, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblDecoStar.setFont(font)
        self.lblDecoStar.setObjectName("lblDecoStar")
        self.lblDecoGift = QtWidgets.QLabel(parent=LoginDialog)
        self.lblDecoGift.setGeometry(QtCore.QRect(565, 400, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblDecoGift.setFont(font)
        self.lblDecoGift.setObjectName("lblDecoGift")
        self.lblDecoBag = QtWidgets.QLabel(parent=LoginDialog)
        self.lblDecoBag.setGeometry(QtCore.QRect(20, 230, 36, 36))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lblDecoBag.setFont(font)
        self.lblDecoBag.setObjectName("lblDecoBag")
        self.lblDecoHeart = QtWidgets.QLabel(parent=LoginDialog)
        self.lblDecoHeart.setGeometry(QtCore.QRect(585, 240, 36, 36))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lblDecoHeart.setFont(font)
        self.lblDecoHeart.setObjectName("lblDecoHeart")
        self.frameLoginShadow = QtWidgets.QFrame(parent=LoginDialog)
        self.frameLoginShadow.setGeometry(QtCore.QRect(143, 53, 380, 430))
        self.frameLoginShadow.setStyleSheet("\n"
"     #frameLoginShadow {\n"
"         background-color: rgba(15, 23, 42, 60);\n"
"         border-radius: 22px;\n"
"     }\n"
"    ")
        self.frameLoginShadow.setObjectName("frameLoginShadow")
        self.frameLoginCard = QtWidgets.QFrame(parent=LoginDialog)
        self.frameLoginCard.setGeometry(QtCore.QRect(135, 45, 380, 430))
        self.frameLoginCard.setStyleSheet("\n"
"     #frameLoginCard {\n"
"         background-color: rgba(255, 255, 255, 245);\n"
"         border-radius: 22px;\n"
"         border: 1px solid rgba(255, 255, 255, 180);\n"
"     }\n"
"     QLabel {\n"
"         color: #1f2937;\n"
"     }\n"
"     QLineEdit {\n"
"         border: 1px solid #e5e7eb;\n"
"         border-radius: 10px;\n"
"         padding: 10px 12px;\n"
"         font-size: 14px;\n"
"         color: #1f2937;\n"
"         background-color: #f9fafb;\n"
"     }\n"
"     QLineEdit:focus {\n"
"         border: 2px solid #a855f7;\n"
"         background-color: #ffffff;\n"
"     }\n"
"     QCheckBox {\n"
"         color: #4b5563;\n"
"         font-size: 13px;\n"
"     }\n"
"     QPushButton#btnLogin {\n"
"         background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"             stop:0 #8b5cf6, stop:0.5 #d946ef, stop:1 #ec4899);\n"
"         color: #ffffff;\n"
"         border-radius: 10px;\n"
"         font-weight: bold;\n"
"         font-size: 14px;\n"
"         height: 42px;\n"
"         border: none;\n"
"     }\n"
"     QPushButton#btnLogin:hover {\n"
"         background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"             stop:0 #7c3aed, stop:0.5 #c026d3, stop:1 #db2777);\n"
"     }\n"
"     QPushButton#btnLogin:pressed {\n"
"         background: #7c3aed;\n"
"     }\n"
"     QPushButton#btnExit {\n"
"         background-color: transparent;\n"
"         border: 1px solid #e5e7eb;\n"
"         color: #6b7280;\n"
"         border-radius: 10px;\n"
"         font-weight: 500;\n"
"         font-size: 14px;\n"
"         height: 42px;\n"
"     }\n"
"     QPushButton#btnExit:hover {\n"
"         background-color: #fdf4ff;\n"
"         color: #a855f7;\n"
"         border: 1px solid #e9d5ff;\n"
"     }\n"
"    ")
        self.frameLoginCard.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameLoginCard.setObjectName("frameLoginCard")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameLoginCard)
        self.verticalLayout_2.setContentsMargins(32, 28, 32, 28)
        self.verticalLayout_2.setSpacing(13)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblLogo = QtWidgets.QLabel(parent=self.frameLoginCard)
        self.lblLogo.setMinimumSize(QtCore.QSize(72, 72))
        self.lblLogo.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lblLogo.setFont(font)
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogo.setStyleSheet("\n"
"        #lblLogo {\n"
"            background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"                stop:0 #a855f7, stop:1 #ec4899);\n"
"            border-radius: 36px;\n"
"        }\n"
"       ")
        self.lblLogo.setObjectName("lblLogo")
        self.verticalLayout_2.addWidget(self.lblLogo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lblTitle = QtWidgets.QLabel(parent=self.frameLoginCard)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(True)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setStyleSheet("color: #7c3aed; font-weight: bold;")
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_2.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=self.frameLoginCard)
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSubtitle.setStyleSheet("color: #9333ea; font-size: 12px; font-weight: 500;")
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_2.addWidget(self.lblSubtitle)
        spacerItem = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.txtUsername = QtWidgets.QLineEdit(parent=self.frameLoginCard)
        self.txtUsername.setObjectName("txtUsername")
        self.verticalLayout_2.addWidget(self.txtUsername)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.frameLoginCard)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.verticalLayout_2.addWidget(self.txtPassword)
        self.chkRememberMe = QtWidgets.QCheckBox(parent=self.frameLoginCard)
        self.chkRememberMe.setObjectName("chkRememberMe")
        self.verticalLayout_2.addWidget(self.chkRememberMe)
        self.lblStatus = QtWidgets.QLabel(parent=self.frameLoginCard)
        self.lblStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblStatus.setText("")
        self.lblStatus.setStyleSheet("color: #ef4444; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_2.addWidget(self.lblStatus)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setSpacing(10)
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.btnExit = QtWidgets.QPushButton(parent=self.frameLoginCard)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_buttons.addWidget(self.btnExit)
        self.btnLogin = QtWidgets.QPushButton(parent=self.frameLoginCard)
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout_buttons.addWidget(self.btnLogin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_buttons)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Đăng nhập - Live Sale Manager"))
        self.lblDecoSparkle1.setText(_translate("LoginDialog", "✨"))
        self.lblDecoConfetti.setText(_translate("LoginDialog", "🎉"))
        self.lblDecoStar.setText(_translate("LoginDialog", "💫"))
        self.lblDecoGift.setText(_translate("LoginDialog", "🎁"))
        self.lblDecoBag.setText(_translate("LoginDialog", "🛒"))
        self.lblDecoHeart.setText(_translate("LoginDialog", "💖"))
        self.lblLogo.setText(_translate("LoginDialog", "🛍️"))
        self.lblTitle.setText(_translate("LoginDialog", "LIVE SALE MANAGER"))
        self.lblSubtitle.setText(_translate("LoginDialog", "✨ Hệ thống Quản lý Livestream Bán hàng ✨"))
        self.txtUsername.setPlaceholderText(_translate("LoginDialog", "👤 Tên đăng nhập"))
        self.txtPassword.setPlaceholderText(_translate("LoginDialog", "🔒 Mật khẩu"))
        self.chkRememberMe.setText(_translate("LoginDialog", "Ghi nhớ đăng nhập"))
        self.btnExit.setText(_translate("LoginDialog", "🚪 Thoát"))
        self.btnLogin.setText(_translate("LoginDialog", "🔑 Đăng nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec())
