# Form implementation generated from reading ui file 'Customer.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomerWidget(object):
    def setupUi(self, CustomerWidget):
        CustomerWidget.setObjectName("CustomerWidget")
        CustomerWidget.resize(900, 600)
        CustomerWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 12px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 8px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 13px;\n"
"        padding: 8px 15px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSearch, QPushButton#btnLuu {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSearch:hover, QPushButton#btnLuu:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnThem {\n"
"        background-color: #10b981;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnThem:hover {\n"
"        background-color: #059669;\n"
"    }\n"
"    QPushButton#btnSua {\n"
"        background-color: #f59e0b;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSua:hover {\n"
"        background-color: #d97706;\n"
"    }\n"
"    QPushButton#btnXoa {\n"
"        background-color: #ef4444;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnXoa:hover {\n"
"        background-color: #dc2626;\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnHuy, QPushButton#btnXuatExcel {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnHuy:hover, QPushButton#btnXuatExcel:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 8px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(CustomerWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=CustomerWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=CustomerWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=CustomerWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutSearch = QtWidgets.QHBoxLayout()
        self.layoutSearch.setSpacing(6)
        self.layoutSearch.setObjectName("layoutSearch")
        self.txtSearch = QtWidgets.QLineEdit(parent=CustomerWidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.layoutSearch.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=CustomerWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.layoutSearch.addWidget(self.btnSearch)
        self.btnRefresh = QtWidgets.QPushButton(parent=CustomerWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutSearch.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutSearch)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutBody = QtWidgets.QHBoxLayout()
        self.layoutBody.setSpacing(15)
        self.layoutBody.setObjectName("layoutBody")
        self.grpKhachHangForm = QtWidgets.QGroupBox(parent=CustomerWidget)
        self.grpKhachHangForm.setMinimumSize(QtCore.QSize(320, 0))
        self.grpKhachHangForm.setMaximumSize(QtCore.QSize(350, 16777215))
        self.grpKhachHangForm.setObjectName("grpKhachHangForm")
        self.verticalLayout_form = QtWidgets.QVBoxLayout(self.grpKhachHangForm)
        self.verticalLayout_form.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_form.setSpacing(12)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.verticalLayout_name = QtWidgets.QVBoxLayout()
        self.verticalLayout_name.setSpacing(4)
        self.verticalLayout_name.setObjectName("verticalLayout_name")
        self.lblTenKhachHang = QtWidgets.QLabel(parent=self.grpKhachHangForm)
        self.lblTenKhachHang.setObjectName("lblTenKhachHang")
        self.verticalLayout_name.addWidget(self.lblTenKhachHang)
        self.txtTenKhachHang = QtWidgets.QLineEdit(parent=self.grpKhachHangForm)
        self.txtTenKhachHang.setObjectName("txtTenKhachHang")
        self.verticalLayout_name.addWidget(self.txtTenKhachHang)
        self.verticalLayout_form.addLayout(self.verticalLayout_name)
        self.verticalLayout_phone = QtWidgets.QVBoxLayout()
        self.verticalLayout_phone.setSpacing(4)
        self.verticalLayout_phone.setObjectName("verticalLayout_phone")
        self.lblSoDienThoai = QtWidgets.QLabel(parent=self.grpKhachHangForm)
        self.lblSoDienThoai.setObjectName("lblSoDienThoai")
        self.verticalLayout_phone.addWidget(self.lblSoDienThoai)
        self.txtSoDienThoai = QtWidgets.QLineEdit(parent=self.grpKhachHangForm)
        self.txtSoDienThoai.setObjectName("txtSoDienThoai")
        self.verticalLayout_phone.addWidget(self.txtSoDienThoai)
        self.verticalLayout_form.addLayout(self.verticalLayout_phone)
        self.verticalLayout_email = QtWidgets.QVBoxLayout()
        self.verticalLayout_email.setSpacing(4)
        self.verticalLayout_email.setObjectName("verticalLayout_email")
        self.lblEmail = QtWidgets.QLabel(parent=self.grpKhachHangForm)
        self.lblEmail.setObjectName("lblEmail")
        self.verticalLayout_email.addWidget(self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(parent=self.grpKhachHangForm)
        self.txtEmail.setObjectName("txtEmail")
        self.verticalLayout_email.addWidget(self.txtEmail)
        self.verticalLayout_form.addLayout(self.verticalLayout_email)
        self.verticalLayout_address = QtWidgets.QVBoxLayout()
        self.verticalLayout_address.setSpacing(4)
        self.verticalLayout_address.setObjectName("verticalLayout_address")
        self.lblDiaChi = QtWidgets.QLabel(parent=self.grpKhachHangForm)
        self.lblDiaChi.setObjectName("lblDiaChi")
        self.verticalLayout_address.addWidget(self.lblDiaChi)
        self.txtDiaChi = QtWidgets.QLineEdit(parent=self.grpKhachHangForm)
        self.txtDiaChi.setObjectName("txtDiaChi")
        self.verticalLayout_address.addWidget(self.txtDiaChi)
        self.verticalLayout_form.addLayout(self.verticalLayout_address)
        self.verticalLayout_joindate = QtWidgets.QVBoxLayout()
        self.verticalLayout_joindate.setSpacing(4)
        self.verticalLayout_joindate.setObjectName("verticalLayout_joindate")
        self.lblNgayThamGia = QtWidgets.QLabel(parent=self.grpKhachHangForm)
        self.lblNgayThamGia.setObjectName("lblNgayThamGia")
        self.verticalLayout_joindate.addWidget(self.lblNgayThamGia)
        self.dateNgayThamGia = QtWidgets.QDateEdit(parent=self.grpKhachHangForm)
        self.dateNgayThamGia.setCalendarPopup(True)
        self.dateNgayThamGia.setObjectName("dateNgayThamGia")
        self.verticalLayout_joindate.addWidget(self.dateNgayThamGia)
        self.verticalLayout_form.addLayout(self.verticalLayout_joindate)
        self.verticalLayout_note = QtWidgets.QVBoxLayout()
        self.verticalLayout_note.setSpacing(4)
        self.verticalLayout_note.setObjectName("verticalLayout_note")
        self.lblGhiChu = QtWidgets.QLabel(parent=self.grpKhachHangForm)
        self.lblGhiChu.setObjectName("lblGhiChu")
        self.verticalLayout_note.addWidget(self.lblGhiChu)
        self.txtGhiChu = QtWidgets.QLineEdit(parent=self.grpKhachHangForm)
        self.txtGhiChu.setObjectName("txtGhiChu")
        self.verticalLayout_note.addWidget(self.txtGhiChu)
        self.verticalLayout_form.addLayout(self.verticalLayout_note)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_form.addItem(spacerItem1)
        self.layoutBody.addWidget(self.grpKhachHangForm)
        self.tblKhachHang = QtWidgets.QTableWidget(parent=CustomerWidget)
        self.tblKhachHang.setObjectName("tblKhachHang")
        self.tblKhachHang.setColumnCount(6)
        self.tblKhachHang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblKhachHang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblKhachHang.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblKhachHang.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblKhachHang.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblKhachHang.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblKhachHang.setHorizontalHeaderItem(5, item)
        self.layoutBody.addWidget(self.tblKhachHang)
        self.verticalLayout_main.addLayout(self.layoutBody)
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setSpacing(10)
        self.layoutActions.setObjectName("layoutActions")
        self.btnThem = QtWidgets.QPushButton(parent=CustomerWidget)
        self.btnThem.setObjectName("btnThem")
        self.layoutActions.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=CustomerWidget)
        self.btnSua.setObjectName("btnSua")
        self.layoutActions.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=CustomerWidget)
        self.btnXoa.setObjectName("btnXoa")
        self.layoutActions.addWidget(self.btnXoa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutActions.addItem(spacerItem2)
        self.btnLuu = QtWidgets.QPushButton(parent=CustomerWidget)
        self.btnLuu.setObjectName("btnLuu")
        self.layoutActions.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=CustomerWidget)
        self.btnHuy.setObjectName("btnHuy")
        self.layoutActions.addWidget(self.btnHuy)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=CustomerWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutActions)
        self.lblStatus = QtWidgets.QLabel(parent=CustomerWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(CustomerWidget)
        QtCore.QMetaObject.connectSlotsByName(CustomerWidget)

    def retranslateUi(self, CustomerWidget):
        _translate = QtCore.QCoreApplication.translate
        CustomerWidget.setWindowTitle(_translate("CustomerWidget", "Quản lý Khách hàng"))
        self.lblIconBadge.setText(_translate("CustomerWidget", "👥"))
        self.lblTitle.setText(_translate("CustomerWidget", "QUẢN LÝ KHÁCH HÀNG (CUSTOMER)"))
        self.lblSubtitle.setText(_translate("CustomerWidget", "Quản lý thông tin khách hàng mua sắm qua livestream"))
        self.txtSearch.setPlaceholderText(_translate("CustomerWidget", "Tìm kiếm theo tên, số điện thoại..."))
        self.btnSearch.setText(_translate("CustomerWidget", "🔍 Tìm kiếm"))
        self.btnRefresh.setText(_translate("CustomerWidget", "🔄 Làm mới"))
        self.grpKhachHangForm.setTitle(_translate("CustomerWidget", "Thông tin khách hàng"))
        self.lblTenKhachHang.setText(_translate("CustomerWidget", "Tên khách hàng:"))
        self.lblSoDienThoai.setText(_translate("CustomerWidget", "Số điện thoại:"))
        self.lblEmail.setText(_translate("CustomerWidget", "Email:"))
        self.lblDiaChi.setText(_translate("CustomerWidget", "Địa chỉ giao hàng:"))
        self.lblNgayThamGia.setText(_translate("CustomerWidget", "Ngày tham gia:"))
        self.lblGhiChu.setText(_translate("CustomerWidget", "Ghi chú:"))
        self.txtGhiChu.setPlaceholderText(_translate("CustomerWidget", "Khách VIP, ưu tiên giao hàng..."))
        item = self.tblKhachHang.horizontalHeaderItem(0)
        item.setText(_translate("CustomerWidget", "Mã Khách Hàng"))
        item = self.tblKhachHang.horizontalHeaderItem(1)
        item.setText(_translate("CustomerWidget", "Tên Khách Hàng"))
        item = self.tblKhachHang.horizontalHeaderItem(2)
        item.setText(_translate("CustomerWidget", "Số Điện Thoại"))
        item = self.tblKhachHang.horizontalHeaderItem(3)
        item.setText(_translate("CustomerWidget", "Email"))
        item = self.tblKhachHang.horizontalHeaderItem(4)
        item.setText(_translate("CustomerWidget", "Địa Chỉ"))
        item = self.tblKhachHang.horizontalHeaderItem(5)
        item.setText(_translate("CustomerWidget", "Ngày Tham Gia"))
        self.btnThem.setText(_translate("CustomerWidget", "➕ Thêm mới"))
        self.btnSua.setText(_translate("CustomerWidget", "✏️ Sửa đổi"))
        self.btnXoa.setText(_translate("CustomerWidget", "🗑️ Xóa bỏ"))
        self.btnLuu.setText(_translate("CustomerWidget", "💾 Lưu lại"))
        self.btnHuy.setText(_translate("CustomerWidget", "❌ Hủy bỏ"))
        self.btnXuatExcel.setText(_translate("CustomerWidget", "📥 Xuất Excel"))
        self.lblStatus.setText(_translate("CustomerWidget", "Trạng thái: Sẵn sàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomerWidget = QtWidgets.QWidget()
    ui = Ui_CustomerWidget()
    ui.setupUi(CustomerWidget)
    CustomerWidget.show()
    sys.exit(app.exec())
