# Form implementation generated from reading ui file 'Seller.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SellerWidget(object):
    def setupUi(self, SellerWidget):
        SellerWidget.setObjectName("SellerWidget")
        SellerWidget.resize(900, 600)
        SellerWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 12px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 8px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 13px;\n"
"        padding: 8px 15px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSearch, QPushButton#btnLuu {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSearch:hover, QPushButton#btnLuu:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnThem {\n"
"        background-color: #10b981;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnThem:hover {\n"
"        background-color: #059669;\n"
"    }\n"
"    QPushButton#btnSua {\n"
"        background-color: #f59e0b;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSua:hover {\n"
"        background-color: #d97706;\n"
"    }\n"
"    QPushButton#btnXoa {\n"
"        background-color: #ef4444;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnXoa:hover {\n"
"        background-color: #dc2626;\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnHuy, QPushButton#btnXuatExcel {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnHuy:hover, QPushButton#btnXuatExcel:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 8px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(SellerWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=SellerWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=SellerWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=SellerWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutSearch = QtWidgets.QHBoxLayout()
        self.layoutSearch.setSpacing(6)
        self.layoutSearch.setObjectName("layoutSearch")
        self.txtSearch = QtWidgets.QLineEdit(parent=SellerWidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.layoutSearch.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=SellerWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.layoutSearch.addWidget(self.btnSearch)
        self.btnRefresh = QtWidgets.QPushButton(parent=SellerWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutSearch.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutSearch)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutBody = QtWidgets.QHBoxLayout()
        self.layoutBody.setSpacing(15)
        self.layoutBody.setObjectName("layoutBody")
        self.grpSellerForm = QtWidgets.QGroupBox(parent=SellerWidget)
        self.grpSellerForm.setMinimumSize(QtCore.QSize(320, 0))
        self.grpSellerForm.setMaximumSize(QtCore.QSize(350, 16777215))
        self.grpSellerForm.setObjectName("grpSellerForm")
        self.verticalLayout_form = QtWidgets.QVBoxLayout(self.grpSellerForm)
        self.verticalLayout_form.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_form.setSpacing(12)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.verticalLayout_name = QtWidgets.QVBoxLayout()
        self.verticalLayout_name.setSpacing(4)
        self.verticalLayout_name.setObjectName("verticalLayout_name")
        self.lblTenNguoiBan = QtWidgets.QLabel(parent=self.grpSellerForm)
        self.lblTenNguoiBan.setObjectName("lblTenNguoiBan")
        self.verticalLayout_name.addWidget(self.lblTenNguoiBan)
        self.txtTenNguoiBan = QtWidgets.QLineEdit(parent=self.grpSellerForm)
        self.txtTenNguoiBan.setObjectName("txtTenNguoiBan")
        self.verticalLayout_name.addWidget(self.txtTenNguoiBan)
        self.verticalLayout_form.addLayout(self.verticalLayout_name)
        self.verticalLayout_phone = QtWidgets.QVBoxLayout()
        self.verticalLayout_phone.setSpacing(4)
        self.verticalLayout_phone.setObjectName("verticalLayout_phone")
        self.lblSoDienThoai = QtWidgets.QLabel(parent=self.grpSellerForm)
        self.lblSoDienThoai.setObjectName("lblSoDienThoai")
        self.verticalLayout_phone.addWidget(self.lblSoDienThoai)
        self.txtSoDienThoai = QtWidgets.QLineEdit(parent=self.grpSellerForm)
        self.txtSoDienThoai.setObjectName("txtSoDienThoai")
        self.verticalLayout_phone.addWidget(self.txtSoDienThoai)
        self.verticalLayout_form.addLayout(self.verticalLayout_phone)
        self.verticalLayout_email = QtWidgets.QVBoxLayout()
        self.verticalLayout_email.setSpacing(4)
        self.verticalLayout_email.setObjectName("verticalLayout_email")
        self.lblEmail = QtWidgets.QLabel(parent=self.grpSellerForm)
        self.lblEmail.setObjectName("lblEmail")
        self.verticalLayout_email.addWidget(self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(parent=self.grpSellerForm)
        self.txtEmail.setObjectName("txtEmail")
        self.verticalLayout_email.addWidget(self.txtEmail)
        self.verticalLayout_form.addLayout(self.verticalLayout_email)
        self.verticalLayout_password = QtWidgets.QVBoxLayout()
        self.verticalLayout_password.setSpacing(4)
        self.verticalLayout_password.setObjectName("verticalLayout_password")
        self.lblMatKhau = QtWidgets.QLabel(parent=self.grpSellerForm)
        self.lblMatKhau.setObjectName("lblMatKhau")
        self.verticalLayout_password.addWidget(self.lblMatKhau)
        self.txtMatKhau = QtWidgets.QLineEdit(parent=self.grpSellerForm)
        self.txtMatKhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtMatKhau.setObjectName("txtMatKhau")
        self.verticalLayout_password.addWidget(self.txtMatKhau)
        self.verticalLayout_form.addLayout(self.verticalLayout_password)
        self.verticalLayout_shop = QtWidgets.QVBoxLayout()
        self.verticalLayout_shop.setSpacing(4)
        self.verticalLayout_shop.setObjectName("verticalLayout_shop")
        self.lblTenShop = QtWidgets.QLabel(parent=self.grpSellerForm)
        self.lblTenShop.setObjectName("lblTenShop")
        self.verticalLayout_shop.addWidget(self.lblTenShop)
        self.txtTenShop = QtWidgets.QLineEdit(parent=self.grpSellerForm)
        self.txtTenShop.setObjectName("txtTenShop")
        self.verticalLayout_shop.addWidget(self.txtTenShop)
        self.verticalLayout_form.addLayout(self.verticalLayout_shop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_form.addItem(spacerItem1)
        self.layoutBody.addWidget(self.grpSellerForm)
        self.tblSeller = QtWidgets.QTableWidget(parent=SellerWidget)
        self.tblSeller.setObjectName("tblSeller")
        self.tblSeller.setColumnCount(5)
        self.tblSeller.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblSeller.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSeller.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSeller.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSeller.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSeller.setHorizontalHeaderItem(4, item)
        self.layoutBody.addWidget(self.tblSeller)
        self.verticalLayout_main.addLayout(self.layoutBody)
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setSpacing(10)
        self.layoutActions.setObjectName("layoutActions")
        self.btnThem = QtWidgets.QPushButton(parent=SellerWidget)
        self.btnThem.setObjectName("btnThem")
        self.layoutActions.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=SellerWidget)
        self.btnSua.setObjectName("btnSua")
        self.layoutActions.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=SellerWidget)
        self.btnXoa.setObjectName("btnXoa")
        self.layoutActions.addWidget(self.btnXoa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutActions.addItem(spacerItem2)
        self.btnLuu = QtWidgets.QPushButton(parent=SellerWidget)
        self.btnLuu.setObjectName("btnLuu")
        self.layoutActions.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=SellerWidget)
        self.btnHuy.setObjectName("btnHuy")
        self.layoutActions.addWidget(self.btnHuy)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=SellerWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutActions)
        self.lblStatus = QtWidgets.QLabel(parent=SellerWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(SellerWidget)
        QtCore.QMetaObject.connectSlotsByName(SellerWidget)

    def retranslateUi(self, SellerWidget):
        _translate = QtCore.QCoreApplication.translate
        SellerWidget.setWindowTitle(_translate("SellerWidget", "Quản lý Người bán"))
        self.lblIconBadge.setText(_translate("SellerWidget", "👤"))
        self.lblTitle.setText(_translate("SellerWidget", "QUẢN LÝ NGƯỜI BÁN (SELLER)"))
        self.lblSubtitle.setText(_translate("SellerWidget", "Quản lý tài khoản người bán và thông tin gian hàng livestream"))
        self.txtSearch.setPlaceholderText(_translate("SellerWidget", "Tìm kiếm theo tên, shop..."))
        self.btnSearch.setText(_translate("SellerWidget", "🔍 Tìm kiếm"))
        self.btnRefresh.setText(_translate("SellerWidget", "🔄 Làm mới"))
        self.grpSellerForm.setTitle(_translate("SellerWidget", "Thông tin người bán"))
        self.lblTenNguoiBan.setText(_translate("SellerWidget", "Tên người bán:"))
        self.lblSoDienThoai.setText(_translate("SellerWidget", "Số điện thoại:"))
        self.lblEmail.setText(_translate("SellerWidget", "Email:"))
        self.lblMatKhau.setText(_translate("SellerWidget", "Mật khẩu đăng nhập:"))
        self.lblTenShop.setText(_translate("SellerWidget", "Tên Shop / Gian hàng:"))
        item = self.tblSeller.horizontalHeaderItem(0)
        item.setText(_translate("SellerWidget", "Mã Người Bán"))
        item = self.tblSeller.horizontalHeaderItem(1)
        item.setText(_translate("SellerWidget", "Tên Người Bán"))
        item = self.tblSeller.horizontalHeaderItem(2)
        item.setText(_translate("SellerWidget", "Số Điện Thoại"))
        item = self.tblSeller.horizontalHeaderItem(3)
        item.setText(_translate("SellerWidget", "Email"))
        item = self.tblSeller.horizontalHeaderItem(4)
        item.setText(_translate("SellerWidget", "Tên Shop"))
        self.btnThem.setText(_translate("SellerWidget", "➕ Thêm mới"))
        self.btnSua.setText(_translate("SellerWidget", "✏️ Sửa đổi"))
        self.btnXoa.setText(_translate("SellerWidget", "🗑️ Xóa bỏ"))
        self.btnLuu.setText(_translate("SellerWidget", "💾 Lưu lại"))
        self.btnHuy.setText(_translate("SellerWidget", "❌ Hủy bỏ"))
        self.btnXuatExcel.setText(_translate("SellerWidget", "📥 Xuất Excel"))
        self.lblStatus.setText(_translate("SellerWidget", "Trạng thái: Sẵn sàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SellerWidget = QtWidgets.QWidget()
    ui = Ui_SellerWidget()
    ui.setupUi(SellerWidget)
    SellerWidget.show()
    sys.exit(app.exec())
