# Form implementation generated from reading ui file 'Order.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OrderWidget(object):
    def setupUi(self, OrderWidget):
        OrderWidget.setObjectName("OrderWidget")
        OrderWidget.resize(1000, 650)
        OrderWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 12px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit, QComboBox, QDateTimeEdit {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 6px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus, QDateTimeEdit:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 11px;\n"
"        padding: 6px 12px;\n"
"        height: 30px;\n"
"    }\n"
"    QPushButton#btnSearch, QPushButton#btnLuu {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font-size: 13px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSearch:hover, QPushButton#btnLuu:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnThem {\n"
"        background-color: #10b981;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font-size: 13px;\n"
"        height: 34px;\n"
"      }\n"
"    QPushButton#btnThem:hover {\n"
"        background-color: #059669;\n"
"    }\n"
"    QPushButton#btnSua {\n"
"        background-color: #f59e0b;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font-size: 13px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSua:hover {\n"
"        background-color: #d97706;\n"
"    }\n"
"    QPushButton#btnXoa {\n"
"        background-color: #ef4444;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"        font-size: 13px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnXoa:hover {\n"
"        background-color: #dc2626;\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnHuy, QPushButton#btnXuatExcel {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"        font-size: 13px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnHuy:hover, QPushButton#btnXuatExcel:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 6px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(OrderWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(12)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=OrderWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=OrderWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=OrderWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutSearch = QtWidgets.QHBoxLayout()
        self.layoutSearch.setSpacing(6)
        self.layoutSearch.setObjectName("layoutSearch")
        self.txtSearch = QtWidgets.QLineEdit(parent=OrderWidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.layoutSearch.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=OrderWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.layoutSearch.addWidget(self.btnSearch)
        self.btnRefresh = QtWidgets.QPushButton(parent=OrderWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutSearch.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutSearch)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutBody = QtWidgets.QHBoxLayout()
        self.layoutBody.setSpacing(15)
        self.layoutBody.setObjectName("layoutBody")
        self.grpOrderForm = QtWidgets.QGroupBox(parent=OrderWidget)
        self.grpOrderForm.setMinimumSize(QtCore.QSize(380, 0))
        self.grpOrderForm.setMaximumSize(QtCore.QSize(400, 16777215))
        self.grpOrderForm.setObjectName("grpOrderForm")
        self.verticalLayout_form = QtWidgets.QVBoxLayout(self.grpOrderForm)
        self.verticalLayout_form.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_form.setSpacing(8)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.horizontalLayout_time_live = QtWidgets.QHBoxLayout()
        self.horizontalLayout_time_live.setSpacing(10)
        self.horizontalLayout_time_live.setObjectName("horizontalLayout_time_live")
        self.verticalLayout_time = QtWidgets.QVBoxLayout()
        self.verticalLayout_time.setSpacing(2)
        self.verticalLayout_time.setObjectName("verticalLayout_time")
        self.lblNgayDat = QtWidgets.QLabel(parent=self.grpOrderForm)
        self.lblNgayDat.setObjectName("lblNgayDat")
        self.verticalLayout_time.addWidget(self.lblNgayDat)
        self.dateNgayDat = QtWidgets.QDateTimeEdit(parent=self.grpOrderForm)
        self.dateNgayDat.setCalendarPopup(True)
        self.dateNgayDat.setObjectName("dateNgayDat")
        self.verticalLayout_time.addWidget(self.dateNgayDat)
        self.horizontalLayout_time_live.addLayout(self.verticalLayout_time)
        self.verticalLayout_live = QtWidgets.QVBoxLayout()
        self.verticalLayout_live.setSpacing(2)
        self.verticalLayout_live.setObjectName("verticalLayout_live")
        self.lblLivestream = QtWidgets.QLabel(parent=self.grpOrderForm)
        self.lblLivestream.setObjectName("lblLivestream")
        self.verticalLayout_live.addWidget(self.lblLivestream)
        self.cbLivestream = QtWidgets.QComboBox(parent=self.grpOrderForm)
        self.cbLivestream.setObjectName("cbLivestream")
        self.verticalLayout_live.addWidget(self.cbLivestream)
        self.horizontalLayout_time_live.addLayout(self.verticalLayout_live)
        self.verticalLayout_form.addLayout(self.horizontalLayout_time_live)
        self.verticalLayout_cust = QtWidgets.QVBoxLayout()
        self.verticalLayout_cust.setSpacing(2)
        self.verticalLayout_cust.setObjectName("verticalLayout_cust")
        self.lblTenKhachHang = QtWidgets.QLabel(parent=self.grpOrderForm)
        self.lblTenKhachHang.setObjectName("lblTenKhachHang")
        self.verticalLayout_cust.addWidget(self.lblTenKhachHang)
        self.txtTenKhachHang = QtWidgets.QLineEdit(parent=self.grpOrderForm)
        self.txtTenKhachHang.setObjectName("txtTenKhachHang")
        self.verticalLayout_cust.addWidget(self.txtTenKhachHang)
        self.verticalLayout_form.addLayout(self.verticalLayout_cust)
        self.verticalLayout_phone = QtWidgets.QVBoxLayout()
        self.verticalLayout_phone.setSpacing(2)
        self.verticalLayout_phone.setObjectName("verticalLayout_phone")
        self.lblSoDienThoai = QtWidgets.QLabel(parent=self.grpOrderForm)
        self.lblSoDienThoai.setObjectName("lblSoDienThoai")
        self.verticalLayout_phone.addWidget(self.lblSoDienThoai)
        self.txtSoDienThoai = QtWidgets.QLineEdit(parent=self.grpOrderForm)
        self.txtSoDienThoai.setObjectName("txtSoDienThoai")
        self.verticalLayout_phone.addWidget(self.txtSoDienThoai)
        self.verticalLayout_form.addLayout(self.verticalLayout_phone)
        self.verticalLayout_addr = QtWidgets.QVBoxLayout()
        self.verticalLayout_addr.setSpacing(2)
        self.verticalLayout_addr.setObjectName("verticalLayout_addr")
        self.lblDiaChiGiao = QtWidgets.QLabel(parent=self.grpOrderForm)
        self.lblDiaChiGiao.setObjectName("lblDiaChiGiao")
        self.verticalLayout_addr.addWidget(self.lblDiaChiGiao)
        self.txtDiaChiGiao = QtWidgets.QLineEdit(parent=self.grpOrderForm)
        self.txtDiaChiGiao.setObjectName("txtDiaChiGiao")
        self.verticalLayout_addr.addWidget(self.txtDiaChiGiao)
        self.verticalLayout_form.addLayout(self.verticalLayout_addr)
        self.verticalLayout_products_list = QtWidgets.QVBoxLayout()
        self.verticalLayout_products_list.setSpacing(2)
        self.verticalLayout_products_list.setObjectName("verticalLayout_products_list")
        self.lblOrderProducts = QtWidgets.QLabel(parent=self.grpOrderForm)
        self.lblOrderProducts.setObjectName("lblOrderProducts")
        self.verticalLayout_products_list.addWidget(self.lblOrderProducts)
        self.tblOrderProductsList = QtWidgets.QTableWidget(parent=self.grpOrderForm)
        self.tblOrderProductsList.setMinimumSize(QtCore.QSize(0, 100))
        self.tblOrderProductsList.setMaximumSize(QtCore.QSize(16777215, 120))
        self.tblOrderProductsList.setStyleSheet("\n"
"               QHeaderView::section {\n"
"                   background-color: #8b5cf6;\n"
"                   color: white;\n"
"               }\n"
"             ")
        self.tblOrderProductsList.setObjectName("tblOrderProductsList")
        self.tblOrderProductsList.setColumnCount(3)
        self.tblOrderProductsList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrderProductsList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrderProductsList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrderProductsList.setHorizontalHeaderItem(2, item)
        self.verticalLayout_products_list.addWidget(self.tblOrderProductsList)
        self.verticalLayout_form.addLayout(self.verticalLayout_products_list)
        self.horizontalLayout_voucher_payment = QtWidgets.QHBoxLayout()
        self.horizontalLayout_voucher_payment.setSpacing(10)
        self.horizontalLayout_voucher_payment.setObjectName("horizontalLayout_voucher_payment")
        self.verticalLayout_voucher = QtWidgets.QVBoxLayout()
        self.verticalLayout_voucher.setSpacing(2)
        self.verticalLayout_voucher.setObjectName("verticalLayout_voucher")
        self.lblVoucher = QtWidgets.QLabel(parent=self.grpOrderForm)
        self.lblVoucher.setObjectName("lblVoucher")
        self.verticalLayout_voucher.addWidget(self.lblVoucher)
        self.cbVoucher = QtWidgets.QComboBox(parent=self.grpOrderForm)
        self.cbVoucher.setObjectName("cbVoucher")
        self.verticalLayout_voucher.addWidget(self.cbVoucher)
        self.horizontalLayout_voucher_payment.addLayout(self.verticalLayout_voucher)
        self.verticalLayout_payment = QtWidgets.QVBoxLayout()
        self.verticalLayout_payment.setSpacing(2)
        self.verticalLayout_payment.setObjectName("verticalLayout_payment")
        self.lblPayment = QtWidgets.QLabel(parent=self.grpOrderForm)
        self.lblPayment.setObjectName("lblPayment")
        self.verticalLayout_payment.addWidget(self.lblPayment)
        self.cbPaymentMode = QtWidgets.QComboBox(parent=self.grpOrderForm)
        self.cbPaymentMode.setObjectName("cbPaymentMode")
        self.cbPaymentMode.addItem("")
        self.cbPaymentMode.addItem("")
        self.cbPaymentMode.addItem("")
        self.verticalLayout_payment.addWidget(self.cbPaymentMode)
        self.horizontalLayout_voucher_payment.addLayout(self.verticalLayout_payment)
        self.verticalLayout_form.addLayout(self.horizontalLayout_voucher_payment)
        self.horizontalLayout_status_total = QtWidgets.QHBoxLayout()
        self.horizontalLayout_status_total.setSpacing(10)
        self.horizontalLayout_status_total.setObjectName("horizontalLayout_status_total")
        self.verticalLayout_status = QtWidgets.QVBoxLayout()
        self.verticalLayout_status.setSpacing(2)
        self.verticalLayout_status.setObjectName("verticalLayout_status")
        self.lblTrangThai = QtWidgets.QLabel(parent=self.grpOrderForm)
        self.lblTrangThai.setObjectName("lblTrangThai")
        self.verticalLayout_status.addWidget(self.lblTrangThai)
        self.cbTrangThai = QtWidgets.QComboBox(parent=self.grpOrderForm)
        self.cbTrangThai.setObjectName("cbTrangThai")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.verticalLayout_status.addWidget(self.cbTrangThai)
        self.horizontalLayout_status_total.addLayout(self.verticalLayout_status)
        self.verticalLayout_total = QtWidgets.QVBoxLayout()
        self.verticalLayout_total.setSpacing(2)
        self.verticalLayout_total.setObjectName("verticalLayout_total")
        self.lblTongTien = QtWidgets.QLabel(parent=self.grpOrderForm)
        self.lblTongTien.setObjectName("lblTongTien")
        self.verticalLayout_total.addWidget(self.lblTongTien)
        self.txtTongTien = QtWidgets.QLineEdit(parent=self.grpOrderForm)
        self.txtTongTien.setReadOnly(True)
        self.txtTongTien.setObjectName("txtTongTien")
        self.verticalLayout_total.addWidget(self.txtTongTien)
        self.horizontalLayout_status_total.addLayout(self.verticalLayout_total)
        self.verticalLayout_form.addLayout(self.horizontalLayout_status_total)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_form.addItem(spacerItem1)
        self.layoutBody.addWidget(self.grpOrderForm)
        self.tblOrder = QtWidgets.QTableWidget(parent=OrderWidget)
        self.tblOrder.setObjectName("tblOrder")
        self.tblOrder.setColumnCount(7)
        self.tblOrder.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrder.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrder.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrder.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrder.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrder.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrder.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrder.setHorizontalHeaderItem(6, item)
        self.layoutBody.addWidget(self.tblOrder)
        self.verticalLayout_main.addLayout(self.layoutBody)
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setSpacing(10)
        self.layoutActions.setObjectName("layoutActions")
        self.btnThem = QtWidgets.QPushButton(parent=OrderWidget)
        self.btnThem.setObjectName("btnThem")
        self.layoutActions.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=OrderWidget)
        self.btnSua.setObjectName("btnSua")
        self.layoutActions.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=OrderWidget)
        self.btnXoa.setObjectName("btnXoa")
        self.layoutActions.addWidget(self.btnXoa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutActions.addItem(spacerItem2)
        self.btnLuu = QtWidgets.QPushButton(parent=OrderWidget)
        self.btnLuu.setObjectName("btnLuu")
        self.layoutActions.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=OrderWidget)
        self.btnHuy.setObjectName("btnHuy")
        self.layoutActions.addWidget(self.btnHuy)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=OrderWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutActions)
        self.lblStatus = QtWidgets.QLabel(parent=OrderWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(OrderWidget)
        QtCore.QMetaObject.connectSlotsByName(OrderWidget)

    def retranslateUi(self, OrderWidget):
        _translate = QtCore.QCoreApplication.translate
        OrderWidget.setWindowTitle(_translate("OrderWidget", "Quản lý Đơn hàng"))
        self.lblIconBadge.setText(_translate("OrderWidget", "🛒"))
        self.lblTitle.setText(_translate("OrderWidget", "QUẢN LÝ ĐƠN HÀNG (ORDERS)"))
        self.lblSubtitle.setText(_translate("OrderWidget", "Quản lý thông tin đơn hàng, danh sách sản phẩm đã chọn, mã giảm giá và trạng thái thanh toán giao nhận"))
        self.txtSearch.setPlaceholderText(_translate("OrderWidget", "Tìm tên khách, số ĐT..."))
        self.btnSearch.setText(_translate("OrderWidget", "🔍 Tìm kiếm"))
        self.btnRefresh.setText(_translate("OrderWidget", "🔄 Làm mới"))
        self.grpOrderForm.setTitle(_translate("OrderWidget", "Chi tiết đơn hàng"))
        self.lblNgayDat.setText(_translate("OrderWidget", "Ngày đặt:"))
        self.lblLivestream.setText(_translate("OrderWidget", "Livestream:"))
        self.lblTenKhachHang.setText(_translate("OrderWidget", "Tên khách hàng:"))
        self.lblSoDienThoai.setText(_translate("OrderWidget", "Số điện thoại:"))
        self.lblDiaChiGiao.setText(_translate("OrderWidget", "Địa chỉ giao hàng:"))
        self.lblOrderProducts.setText(_translate("OrderWidget", "Sản phẩm đã chọn mua:"))
        item = self.tblOrderProductsList.horizontalHeaderItem(0)
        item.setText(_translate("OrderWidget", "Sản Phẩm"))
        item = self.tblOrderProductsList.horizontalHeaderItem(1)
        item.setText(_translate("OrderWidget", "SL"))
        item = self.tblOrderProductsList.horizontalHeaderItem(2)
        item.setText(_translate("OrderWidget", "Đơn Giá"))
        self.lblVoucher.setText(_translate("OrderWidget", "Voucher:"))
        self.lblPayment.setText(_translate("OrderWidget", "Thanh toán:"))
        self.cbPaymentMode.setItemText(0, _translate("OrderWidget", "Tiền mặt"))
        self.cbPaymentMode.setItemText(1, _translate("OrderWidget", "Chuyển khoản"))
        self.cbPaymentMode.setItemText(2, _translate("OrderWidget", "Ví điện tử"))
        self.lblTrangThai.setText(_translate("OrderWidget", "Trạng thái đơn:"))
        self.cbTrangThai.setItemText(0, _translate("OrderWidget", "Chờ xác nhận"))
        self.cbTrangThai.setItemText(1, _translate("OrderWidget", "Đã xác nhận"))
        self.cbTrangThai.setItemText(2, _translate("OrderWidget", "Đang giao"))
        self.cbTrangThai.setItemText(3, _translate("OrderWidget", "Đã giao"))
        self.cbTrangThai.setItemText(4, _translate("OrderWidget", "Đã hủy"))
        self.lblTongTien.setText(_translate("OrderWidget", "Tổng tiền (VND):"))
        self.txtTongTien.setText(_translate("OrderWidget", "0"))
        item = self.tblOrder.horizontalHeaderItem(0)
        item.setText(_translate("OrderWidget", "Mã Hóa Đơn"))
        item = self.tblOrder.horizontalHeaderItem(1)
        item.setText(_translate("OrderWidget", "Ngày Đặt"))
        item = self.tblOrder.horizontalHeaderItem(2)
        item.setText(_translate("OrderWidget", "Khách Hàng"))
        item = self.tblOrder.horizontalHeaderItem(3)
        item.setText(_translate("OrderWidget", "Số Điện Thoại"))
        item = self.tblOrder.horizontalHeaderItem(4)
        item.setText(_translate("OrderWidget", "Tổng Tiền"))
        item = self.tblOrder.horizontalHeaderItem(5)
        item.setText(_translate("OrderWidget", "Voucher"))
        item = self.tblOrder.horizontalHeaderItem(6)
        item.setText(_translate("OrderWidget", "Trạng Thái"))
        self.btnThem.setText(_translate("OrderWidget", "➕ Thêm mới"))
        self.btnSua.setText(_translate("OrderWidget", "✏️ Sửa đổi"))
        self.btnXoa.setText(_translate("OrderWidget", "🗑️ Xóa bỏ"))
        self.btnLuu.setText(_translate("OrderWidget", "💾 Lưu lại"))
        self.btnHuy.setText(_translate("OrderWidget", "❌ Hủy bỏ"))
        self.btnXuatExcel.setText(_translate("OrderWidget", "📥 Xuất Excel"))
        self.lblStatus.setText(_translate("OrderWidget", "Trạng thái: Sẵn sàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrderWidget = QtWidgets.QWidget()
    ui = Ui_OrderWidget()
    ui.setupUi(OrderWidget)
    OrderWidget.show()
    sys.exit(app.exec())
