# Form implementation generated from reading ui file 'Voucher.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VoucherWidget(object):
    def setupUi(self, VoucherWidget):
        VoucherWidget.setObjectName("VoucherWidget")
        VoucherWidget.resize(950, 600)
        VoucherWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 12px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit, QComboBox, QDateEdit {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 8px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus, QDateEdit:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 13px;\n"
"        padding: 8px 15px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSearch, QPushButton#btnLuu {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSearch:hover, QPushButton#btnLuu:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnThem {\n"
"        background-color: #10b981;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnThem:hover {\n"
"        background-color: #059669;\n"
"    }\n"
"    QPushButton#btnSua {\n"
"        background-color: #f59e0b;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSua:hover {\n"
"        background-color: #d97706;\n"
"    }\n"
"    QPushButton#btnXoa {\n"
"        background-color: #ef4444;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnXoa:hover {\n"
"        background-color: #dc2626;\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnHuy, QPushButton#btnXuatExcel {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnHuy:hover, QPushButton#btnXuatExcel:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 8px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(VoucherWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=VoucherWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=VoucherWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=VoucherWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutSearch = QtWidgets.QHBoxLayout()
        self.layoutSearch.setSpacing(6)
        self.layoutSearch.setObjectName("layoutSearch")
        self.txtSearch = QtWidgets.QLineEdit(parent=VoucherWidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.layoutSearch.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=VoucherWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.layoutSearch.addWidget(self.btnSearch)
        self.btnRefresh = QtWidgets.QPushButton(parent=VoucherWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutSearch.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutSearch)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutBody = QtWidgets.QHBoxLayout()
        self.layoutBody.setSpacing(15)
        self.layoutBody.setObjectName("layoutBody")
        self.grpVoucherForm = QtWidgets.QGroupBox(parent=VoucherWidget)
        self.grpVoucherForm.setMinimumSize(QtCore.QSize(330, 0))
        self.grpVoucherForm.setMaximumSize(QtCore.QSize(360, 16777215))
        self.grpVoucherForm.setObjectName("grpVoucherForm")
        self.verticalLayout_form = QtWidgets.QVBoxLayout(self.grpVoucherForm)
        self.verticalLayout_form.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_form.setSpacing(10)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.verticalLayout_code = QtWidgets.QVBoxLayout()
        self.verticalLayout_code.setSpacing(4)
        self.verticalLayout_code.setObjectName("verticalLayout_code")
        self.lblMaVoucher = QtWidgets.QLabel(parent=self.grpVoucherForm)
        self.lblMaVoucher.setObjectName("lblMaVoucher")
        self.verticalLayout_code.addWidget(self.lblMaVoucher)
        self.txtMaVoucher = QtWidgets.QLineEdit(parent=self.grpVoucherForm)
        self.txtMaVoucher.setObjectName("txtMaVoucher")
        self.verticalLayout_code.addWidget(self.txtMaVoucher)
        self.verticalLayout_form.addLayout(self.verticalLayout_code)
        self.horizontalLayout_discount = QtWidgets.QHBoxLayout()
        self.horizontalLayout_discount.setSpacing(10)
        self.horizontalLayout_discount.setObjectName("horizontalLayout_discount")
        self.verticalLayout_type = QtWidgets.QVBoxLayout()
        self.verticalLayout_type.setSpacing(4)
        self.verticalLayout_type.setObjectName("verticalLayout_type")
        self.lblLoaiVoucher = QtWidgets.QLabel(parent=self.grpVoucherForm)
        self.lblLoaiVoucher.setObjectName("lblLoaiVoucher")
        self.verticalLayout_type.addWidget(self.lblLoaiVoucher)
        self.cbLoaiVoucher = QtWidgets.QComboBox(parent=self.grpVoucherForm)
        self.cbLoaiVoucher.setObjectName("cbLoaiVoucher")
        self.cbLoaiVoucher.addItem("")
        self.cbLoaiVoucher.addItem("")
        self.verticalLayout_type.addWidget(self.cbLoaiVoucher)
        self.horizontalLayout_discount.addLayout(self.verticalLayout_type)
        self.verticalLayout_val = QtWidgets.QVBoxLayout()
        self.verticalLayout_val.setSpacing(4)
        self.verticalLayout_val.setObjectName("verticalLayout_val")
        self.lblGiaTriGiam = QtWidgets.QLabel(parent=self.grpVoucherForm)
        self.lblGiaTriGiam.setObjectName("lblGiaTriGiam")
        self.verticalLayout_val.addWidget(self.lblGiaTriGiam)
        self.txtGiaTriGiam = QtWidgets.QLineEdit(parent=self.grpVoucherForm)
        self.txtGiaTriGiam.setObjectName("txtGiaTriGiam")
        self.verticalLayout_val.addWidget(self.txtGiaTriGiam)
        self.horizontalLayout_discount.addLayout(self.verticalLayout_val)
        self.verticalLayout_form.addLayout(self.horizontalLayout_discount)
        self.horizontalLayout_limits = QtWidgets.QHBoxLayout()
        self.horizontalLayout_limits.setSpacing(10)
        self.horizontalLayout_limits.setObjectName("horizontalLayout_limits")
        self.verticalLayout_min = QtWidgets.QVBoxLayout()
        self.verticalLayout_min.setSpacing(4)
        self.verticalLayout_min.setObjectName("verticalLayout_min")
        self.lblDonHangToiThieu = QtWidgets.QLabel(parent=self.grpVoucherForm)
        self.lblDonHangToiThieu.setObjectName("lblDonHangToiThieu")
        self.verticalLayout_min.addWidget(self.lblDonHangToiThieu)
        self.txtDonHangToiThieu = QtWidgets.QLineEdit(parent=self.grpVoucherForm)
        self.txtDonHangToiThieu.setObjectName("txtDonHangToiThieu")
        self.verticalLayout_min.addWidget(self.txtDonHangToiThieu)
        self.horizontalLayout_limits.addLayout(self.verticalLayout_min)
        self.verticalLayout_max = QtWidgets.QVBoxLayout()
        self.verticalLayout_max.setSpacing(4)
        self.verticalLayout_max.setObjectName("verticalLayout_max")
        self.lblGiamToiDa = QtWidgets.QLabel(parent=self.grpVoucherForm)
        self.lblGiamToiDa.setObjectName("lblGiamToiDa")
        self.verticalLayout_max.addWidget(self.lblGiamToiDa)
        self.txtGiamToiDa = QtWidgets.QLineEdit(parent=self.grpVoucherForm)
        self.txtGiamToiDa.setObjectName("txtGiamToiDa")
        self.verticalLayout_max.addWidget(self.txtGiamToiDa)
        self.horizontalLayout_limits.addLayout(self.verticalLayout_max)
        self.verticalLayout_form.addLayout(self.horizontalLayout_limits)
        self.horizontalLayout_dates = QtWidgets.QHBoxLayout()
        self.horizontalLayout_dates.setSpacing(10)
        self.horizontalLayout_dates.setObjectName("horizontalLayout_dates")
        self.verticalLayout_start = QtWidgets.QVBoxLayout()
        self.verticalLayout_start.setSpacing(4)
        self.verticalLayout_start.setObjectName("verticalLayout_start")
        self.lblNgayBatDau = QtWidgets.QLabel(parent=self.grpVoucherForm)
        self.lblNgayBatDau.setObjectName("lblNgayBatDau")
        self.verticalLayout_start.addWidget(self.lblNgayBatDau)
        self.dateStart = QtWidgets.QDateEdit(parent=self.grpVoucherForm)
        self.dateStart.setCalendarPopup(True)
        self.dateStart.setObjectName("dateStart")
        self.verticalLayout_start.addWidget(self.dateStart)
        self.horizontalLayout_dates.addLayout(self.verticalLayout_start)
        self.verticalLayout_end = QtWidgets.QVBoxLayout()
        self.verticalLayout_end.setSpacing(4)
        self.verticalLayout_end.setObjectName("verticalLayout_end")
        self.lblNgayKetThuc = QtWidgets.QLabel(parent=self.grpVoucherForm)
        self.lblNgayKetThuc.setObjectName("lblNgayKetThuc")
        self.verticalLayout_end.addWidget(self.lblNgayKetThuc)
        self.dateEnd = QtWidgets.QDateEdit(parent=self.grpVoucherForm)
        self.dateEnd.setCalendarPopup(True)
        self.dateEnd.setObjectName("dateEnd")
        self.verticalLayout_end.addWidget(self.dateEnd)
        self.horizontalLayout_dates.addLayout(self.verticalLayout_end)
        self.verticalLayout_form.addLayout(self.horizontalLayout_dates)
        self.verticalLayout_status = QtWidgets.QVBoxLayout()
        self.verticalLayout_status.setSpacing(4)
        self.verticalLayout_status.setObjectName("verticalLayout_status")
        self.lblTrangThai = QtWidgets.QLabel(parent=self.grpVoucherForm)
        self.lblTrangThai.setObjectName("lblTrangThai")
        self.verticalLayout_status.addWidget(self.lblTrangThai)
        self.cbKichHoat = QtWidgets.QComboBox(parent=self.grpVoucherForm)
        self.cbKichHoat.setObjectName("cbKichHoat")
        self.cbKichHoat.addItem("")
        self.cbKichHoat.addItem("")
        self.verticalLayout_status.addWidget(self.cbKichHoat)
        self.verticalLayout_form.addLayout(self.verticalLayout_status)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_form.addItem(spacerItem1)
        self.layoutBody.addWidget(self.grpVoucherForm)
        self.tblVoucher = QtWidgets.QTableWidget(parent=VoucherWidget)
        self.tblVoucher.setObjectName("tblVoucher")
        self.tblVoucher.setColumnCount(8)
        self.tblVoucher.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblVoucher.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVoucher.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVoucher.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVoucher.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVoucher.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVoucher.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVoucher.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVoucher.setHorizontalHeaderItem(7, item)
        self.layoutBody.addWidget(self.tblVoucher)
        self.verticalLayout_main.addLayout(self.layoutBody)
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setSpacing(10)
        self.layoutActions.setObjectName("layoutActions")
        self.btnThem = QtWidgets.QPushButton(parent=VoucherWidget)
        self.btnThem.setObjectName("btnThem")
        self.layoutActions.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=VoucherWidget)
        self.btnSua.setObjectName("btnSua")
        self.layoutActions.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=VoucherWidget)
        self.btnXoa.setObjectName("btnXoa")
        self.layoutActions.addWidget(self.btnXoa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutActions.addItem(spacerItem2)
        self.btnLuu = QtWidgets.QPushButton(parent=VoucherWidget)
        self.btnLuu.setObjectName("btnLuu")
        self.layoutActions.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=VoucherWidget)
        self.btnHuy.setObjectName("btnHuy")
        self.layoutActions.addWidget(self.btnHuy)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=VoucherWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutActions)
        self.lblStatus = QtWidgets.QLabel(parent=VoucherWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(VoucherWidget)
        QtCore.QMetaObject.connectSlotsByName(VoucherWidget)

    def retranslateUi(self, VoucherWidget):
        _translate = QtCore.QCoreApplication.translate
        VoucherWidget.setWindowTitle(_translate("VoucherWidget", "Quản lý Mã giảm giá (Voucher)"))
        self.lblIconBadge.setText(_translate("VoucherWidget", "🎟️"))
        self.lblTitle.setText(_translate("VoucherWidget", "DANH SÁCH MÃ GIẢM GIÁ (VOUCHER)"))
        self.lblSubtitle.setText(_translate("VoucherWidget", "Quản lý các chương trình ưu đãi, giá trị giảm giá, và điều kiện áp dụng hóa đơn của Voucher"))
        self.txtSearch.setPlaceholderText(_translate("VoucherWidget", "Tìm mã hoặc loại voucher..."))
        self.btnSearch.setText(_translate("VoucherWidget", "🔍 Tìm kiếm"))
        self.btnRefresh.setText(_translate("VoucherWidget", "🔄 Làm mới"))
        self.grpVoucherForm.setTitle(_translate("VoucherWidget", "Thông tin Voucher"))
        self.lblMaVoucher.setText(_translate("VoucherWidget", "Mã giảm giá:"))
        self.lblLoaiVoucher.setText(_translate("VoucherWidget", "Loại Voucher:"))
        self.cbLoaiVoucher.setItemText(0, _translate("VoucherWidget", "Phần trăm (%)"))
        self.cbLoaiVoucher.setItemText(1, _translate("VoucherWidget", "Số tiền cố định (VND)"))
        self.lblGiaTriGiam.setText(_translate("VoucherWidget", "Giá trị giảm:"))
        self.lblDonHangToiThieu.setText(_translate("VoucherWidget", "Tối thiểu ĐH:"))
        self.lblGiamToiDa.setText(_translate("VoucherWidget", "Giảm tối đa:"))
        self.lblNgayBatDau.setText(_translate("VoucherWidget", "Từ ngày:"))
        self.lblNgayKetThuc.setText(_translate("VoucherWidget", "Đến ngày:"))
        self.lblTrangThai.setText(_translate("VoucherWidget", "Trạng thái kích hoạt:"))
        self.cbKichHoat.setItemText(0, _translate("VoucherWidget", "Đang kích hoạt"))
        self.cbKichHoat.setItemText(1, _translate("VoucherWidget", "Tạm ngưng"))
        item = self.tblVoucher.horizontalHeaderItem(0)
        item.setText(_translate("VoucherWidget", "Mã Voucher"))
        item = self.tblVoucher.horizontalHeaderItem(1)
        item.setText(_translate("VoucherWidget", "Loại Ưu Đãi"))
        item = self.tblVoucher.horizontalHeaderItem(2)
        item.setText(_translate("VoucherWidget", "Mức Chiết Khấu"))
        item = self.tblVoucher.horizontalHeaderItem(3)
        item.setText(_translate("VoucherWidget", "Tối Thiểu ĐH"))
        item = self.tblVoucher.horizontalHeaderItem(4)
        item.setText(_translate("VoucherWidget", "Giảm Tối Đa"))
        item = self.tblVoucher.horizontalHeaderItem(5)
        item.setText(_translate("VoucherWidget", "Thời Hạn Từ ngày"))
        item = self.tblVoucher.horizontalHeaderItem(6)
        item.setText(_translate("VoucherWidget", "Thời Hạn Đến ngày"))
        item = self.tblVoucher.horizontalHeaderItem(7)
        item.setText(_translate("VoucherWidget", "Trạng Thái"))
        self.btnThem.setText(_translate("VoucherWidget", "➕ Thêm mới"))
        self.btnSua.setText(_translate("VoucherWidget", "✏️ Sửa đổi"))
        self.btnXoa.setText(_translate("VoucherWidget", "🗑️ Xóa bỏ"))
        self.btnLuu.setText(_translate("VoucherWidget", "💾 Lưu lại"))
        self.btnHuy.setText(_translate("VoucherWidget", "❌ Hủy bỏ"))
        self.btnXuatExcel.setText(_translate("VoucherWidget", "📥 Xuất Excel"))
        self.lblStatus.setText(_translate("VoucherWidget", "Trạng thái: Sẵn sàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoucherWidget = QtWidgets.QWidget()
    ui = Ui_VoucherWidget()
    ui.setupUi(VoucherWidget)
    VoucherWidget.show()
    sys.exit(app.exec())
