# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"    QMainWindow {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"    }\n"
"    QWidget#centralwidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"    }\n"
"    QFrame#widgetSidebar {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1e1b4b, stop:1 #4c1d95);\n"
"        max-width: 240px;\n"
"        min-width: 240px;\n"
"    }\n"
"    QLabel#lblSidebarTitle {\n"
"        color: #ffffff;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QLabel#lblSidebarSubtitle {\n"
"        color: #c4b5fd;\n"
"        font-size: 11px;\n"
"    }\n"
"    QPushButton.menu-btn {\n"
"        background-color: transparent;\n"
"        color: #ddd6fe;\n"
"        border: none;\n"
"        border-radius: 6px;\n"
"        padding: 10px 15px;\n"
"        text-align: left;\n"
"        font-size: 13px;\n"
"        font-weight: 500;\n"
"        margin: 2px 10px;\n"
"    }\n"
"    QPushButton.menu-btn:hover {\n"
"        background-color: rgba(255, 255, 255, 25);\n"
"        color: #ffffff;\n"
"    }\n"
"    QPushButton.menu-btn:checked {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #a855f7, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"    }\n"
"    QPushButton#btnMenuLogout {\n"
"        color: #fca5a5;\n"
"    }\n"
"    QPushButton#btnMenuLogout:hover {\n"
"        background-color: #7f1d1d;\n"
"        color: #ffffff;\n"
"    }\n"
"    QFrame#frameHeader {\n"
"        background-color: #ffffff;\n"
"        border-bottom: 1px solid #e9d5ff;\n"
"        max-height: 60px;\n"
"        min-height: 60px;\n"
"    }\n"
"    QLabel#lblHeaderTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #4c1d95;\n"
"    }\n"
"    QLabel#lblUserScope {\n"
"        font-size: 13px;\n"
"        color: #64748b;\n"
"    }\n"
"    QFrame.stats-card {\n"
"        background-color: #ffffff;\n"
"        border-radius: 12px;\n"
"        border: 1px solid #f3e8ff;\n"
"    }\n"
"    QLabel.card-num {\n"
"        font-size: 24px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QLabel.card-title {\n"
"        font-size: 12px;\n"
"        color: #64748b;\n"
"        font-weight: 500;\n"
"    }\n"
"    QLabel.card-icon {\n"
"        font-size: 22px;\n"
"        min-width: 46px;\n"
"        max-width: 46px;\n"
"        min-height: 46px;\n"
"        max-height: 46px;\n"
"        border-radius: 23px;\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"    }\n"
"    QFrame#cardCustomer { border-left: 4px solid #ec4899; }\n"
"    QFrame#cardLivestream { border-left: 4px solid #7c3aed; }\n"
"    QFrame#cardProduct { border-left: 4px solid #10b981; }\n"
"    QFrame#cardOrder { border-left: 4px solid #f59e0b; }\n"
"    QFrame#cardRevenue { border-left: 4px solid #22d3ee; }\n"
"    QFrame#cardVoucher { border-left: 4px solid #fb923c; }\n"
"    \n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QTableWidget::item {\n"
"        padding: 5px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #f1f5f9;\n"
"        color: #475569;\n"
"        font-weight: bold;\n"
"        border: none;\n"
"        padding: 6px;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_main.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_main.setSpacing(0)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.widgetSidebar = QtWidgets.QFrame(parent=self.centralwidget)
        self.widgetSidebar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.widgetSidebar.setObjectName("widgetSidebar")
        self.verticalLayout_sidebar = QtWidgets.QVBoxLayout(self.widgetSidebar)
        self.verticalLayout_sidebar.setContentsMargins(0, 20, 0, 20)
        self.verticalLayout_sidebar.setSpacing(4)
        self.verticalLayout_sidebar.setObjectName("verticalLayout_sidebar")
        self.layoutLogo = QtWidgets.QVBoxLayout()
        self.layoutLogo.setContentsMargins(20, -1, 20, 15)
        self.layoutLogo.setSpacing(2)
        self.layoutLogo.setObjectName("layoutLogo")
        self.lblSidebarLogo = QtWidgets.QLabel(parent=self.widgetSidebar)
        self.lblSidebarLogo.setMinimumSize(QtCore.QSize(56, 56))
        self.lblSidebarLogo.setMaximumSize(QtCore.QSize(56, 56))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lblSidebarLogo.setFont(font)
        self.lblSidebarLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSidebarLogo.setStyleSheet("\n"
"             #lblSidebarLogo {\n"
"                 background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"                 border-radius: 28px;\n"
"                 margin-bottom: 6px;\n"
"             }\n"
"            ")
        self.lblSidebarLogo.setObjectName("lblSidebarLogo")
        self.layoutLogo.addWidget(self.lblSidebarLogo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lblSidebarTitle = QtWidgets.QLabel(parent=self.widgetSidebar)
        self.lblSidebarTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSidebarTitle.setObjectName("lblSidebarTitle")
        self.layoutLogo.addWidget(self.lblSidebarTitle)
        self.lblSidebarSubtitle = QtWidgets.QLabel(parent=self.widgetSidebar)
        self.lblSidebarSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSidebarSubtitle.setObjectName("lblSidebarSubtitle")
        self.layoutLogo.addWidget(self.lblSidebarSubtitle)
        self.verticalLayout_sidebar.addLayout(self.layoutLogo)
        self.lineSidebarDivider = QtWidgets.QFrame(parent=self.widgetSidebar)
        self.lineSidebarDivider.setMinimumSize(QtCore.QSize(0, 1))
        self.lineSidebarDivider.setMaximumSize(QtCore.QSize(16777215, 1))
        self.lineSidebarDivider.setStyleSheet("background-color: rgba(255, 255, 255, 30); margin: 0px 20px;")
        self.lineSidebarDivider.setObjectName("lineSidebarDivider")
        self.verticalLayout_sidebar.addWidget(self.lineSidebarDivider)
        self.btnMenuDashboard = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuDashboard.setCheckable(True)
        self.btnMenuDashboard.setChecked(True)
        self.btnMenuDashboard.setAutoExclusive(True)
        self.btnMenuDashboard.setObjectName("btnMenuDashboard")
        self.verticalLayout_sidebar.addWidget(self.btnMenuDashboard)
        self.btnMenuSeller = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuSeller.setCheckable(True)
        self.btnMenuSeller.setAutoExclusive(True)
        self.btnMenuSeller.setObjectName("btnMenuSeller")
        self.verticalLayout_sidebar.addWidget(self.btnMenuSeller)
        self.btnMenuCustomer = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuCustomer.setCheckable(True)
        self.btnMenuCustomer.setAutoExclusive(True)
        self.btnMenuCustomer.setObjectName("btnMenuCustomer")
        self.verticalLayout_sidebar.addWidget(self.btnMenuCustomer)
        self.btnMenuLivestream = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuLivestream.setCheckable(True)
        self.btnMenuLivestream.setAutoExclusive(True)
        self.btnMenuLivestream.setObjectName("btnMenuLivestream")
        self.verticalLayout_sidebar.addWidget(self.btnMenuLivestream)
        self.btnMenuProduct = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuProduct.setCheckable(True)
        self.btnMenuProduct.setAutoExclusive(True)
        self.btnMenuProduct.setObjectName("btnMenuProduct")
        self.verticalLayout_sidebar.addWidget(self.btnMenuProduct)
        self.btnMenuLivestreamDetail = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuLivestreamDetail.setCheckable(True)
        self.btnMenuLivestreamDetail.setAutoExclusive(True)
        self.btnMenuLivestreamDetail.setObjectName("btnMenuLivestreamDetail")
        self.verticalLayout_sidebar.addWidget(self.btnMenuLivestreamDetail)
        self.btnMenuComment = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuComment.setCheckable(True)
        self.btnMenuComment.setAutoExclusive(True)
        self.btnMenuComment.setObjectName("btnMenuComment")
        self.verticalLayout_sidebar.addWidget(self.btnMenuComment)
        self.btnMenuOrder = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuOrder.setCheckable(True)
        self.btnMenuOrder.setAutoExclusive(True)
        self.btnMenuOrder.setObjectName("btnMenuOrder")
        self.verticalLayout_sidebar.addWidget(self.btnMenuOrder)
        self.btnMenuOrderDetail = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuOrderDetail.setCheckable(True)
        self.btnMenuOrderDetail.setAutoExclusive(True)
        self.btnMenuOrderDetail.setObjectName("btnMenuOrderDetail")
        self.verticalLayout_sidebar.addWidget(self.btnMenuOrderDetail)
        self.btnMenuVoucher = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuVoucher.setCheckable(True)
        self.btnMenuVoucher.setAutoExclusive(True)
        self.btnMenuVoucher.setObjectName("btnMenuVoucher")
        self.verticalLayout_sidebar.addWidget(self.btnMenuVoucher)
        self.btnMenuPayment = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuPayment.setCheckable(True)
        self.btnMenuPayment.setAutoExclusive(True)
        self.btnMenuPayment.setObjectName("btnMenuPayment")
        self.verticalLayout_sidebar.addWidget(self.btnMenuPayment)
        self.btnMenuStatistics = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuStatistics.setCheckable(True)
        self.btnMenuStatistics.setAutoExclusive(True)
        self.btnMenuStatistics.setObjectName("btnMenuStatistics")
        self.verticalLayout_sidebar.addWidget(self.btnMenuStatistics)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_sidebar.addItem(spacerItem)
        self.btnMenuLogout = QtWidgets.QPushButton(parent=self.widgetSidebar)
        self.btnMenuLogout.setCheckable(False)
        self.btnMenuLogout.setObjectName("btnMenuLogout")
        self.verticalLayout_sidebar.addWidget(self.btnMenuLogout)
        self.horizontalLayout_main.addWidget(self.widgetSidebar)
        self.verticalLayout_content = QtWidgets.QVBoxLayout()
        self.verticalLayout_content.setSpacing(0)
        self.verticalLayout_content.setObjectName("verticalLayout_content")
        self.frameHeader = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameHeader.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameHeader.setObjectName("frameHeader")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout(self.frameHeader)
        self.horizontalLayout_header.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        self.lblHeaderTitle = QtWidgets.QLabel(parent=self.frameHeader)
        self.lblHeaderTitle.setObjectName("lblHeaderTitle")
        self.horizontalLayout_header.addWidget(self.lblHeaderTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_header.addItem(spacerItem1)
        self.lblUserScope = QtWidgets.QLabel(parent=self.frameHeader)
        self.lblUserScope.setObjectName("lblUserScope")
        self.horizontalLayout_header.addWidget(self.lblUserScope)
        self.verticalLayout_content.addWidget(self.frameHeader)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageDashboard = QtWidgets.QWidget()
        self.pageDashboard.setObjectName("pageDashboard")
        self.verticalLayout_page = QtWidgets.QVBoxLayout(self.pageDashboard)
        self.verticalLayout_page.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_page.setSpacing(20)
        self.verticalLayout_page.setObjectName("verticalLayout_page")
        self.layoutStatsCards = QtWidgets.QHBoxLayout()
        self.layoutStatsCards.setSpacing(15)
        self.layoutStatsCards.setObjectName("layoutStatsCards")
        self.cardCustomer = QtWidgets.QFrame(parent=self.pageDashboard)
        self.cardCustomer.setObjectName("cardCustomer")
        self.horizontalLayout_card0 = QtWidgets.QHBoxLayout(self.cardCustomer)
        self.horizontalLayout_card0.setObjectName("horizontalLayout_card0")
        self.verticalLayout_card0_text = QtWidgets.QVBoxLayout()
        self.verticalLayout_card0_text.setObjectName("verticalLayout_card0_text")
        self.lblCardCustomerNum = QtWidgets.QLabel(parent=self.cardCustomer)
        self.lblCardCustomerNum.setObjectName("lblCardCustomerNum")
        self.verticalLayout_card0_text.addWidget(self.lblCardCustomerNum)
        self.lblCardCustomerTitle = QtWidgets.QLabel(parent=self.cardCustomer)
        self.lblCardCustomerTitle.setObjectName("lblCardCustomerTitle")
        self.verticalLayout_card0_text.addWidget(self.lblCardCustomerTitle)
        self.horizontalLayout_card0.addLayout(self.verticalLayout_card0_text)
        self.lblCardCustomerIcon = QtWidgets.QLabel(parent=self.cardCustomer)
        self.lblCardCustomerIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCardCustomerIcon.setObjectName("lblCardCustomerIcon")
        self.horizontalLayout_card0.addWidget(self.lblCardCustomerIcon)
        self.layoutStatsCards.addWidget(self.cardCustomer)
        self.cardLivestream = QtWidgets.QFrame(parent=self.pageDashboard)
        self.cardLivestream.setObjectName("cardLivestream")
        self.horizontalLayout_card1 = QtWidgets.QHBoxLayout(self.cardLivestream)
        self.horizontalLayout_card1.setObjectName("horizontalLayout_card1")
        self.verticalLayout_card1_text = QtWidgets.QVBoxLayout()
        self.verticalLayout_card1_text.setObjectName("verticalLayout_card1_text")
        self.lblCardLivestreamNum = QtWidgets.QLabel(parent=self.cardLivestream)
        self.lblCardLivestreamNum.setObjectName("lblCardLivestreamNum")
        self.verticalLayout_card1_text.addWidget(self.lblCardLivestreamNum)
        self.lblCardLivestreamTitle = QtWidgets.QLabel(parent=self.cardLivestream)
        self.lblCardLivestreamTitle.setObjectName("lblCardLivestreamTitle")
        self.verticalLayout_card1_text.addWidget(self.lblCardLivestreamTitle)
        self.horizontalLayout_card1.addLayout(self.verticalLayout_card1_text)
        self.lblCardLivestreamIcon = QtWidgets.QLabel(parent=self.cardLivestream)
        self.lblCardLivestreamIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCardLivestreamIcon.setObjectName("lblCardLivestreamIcon")
        self.horizontalLayout_card1.addWidget(self.lblCardLivestreamIcon)
        self.layoutStatsCards.addWidget(self.cardLivestream)
        self.cardProduct = QtWidgets.QFrame(parent=self.pageDashboard)
        self.cardProduct.setObjectName("cardProduct")
        self.horizontalLayout_card2 = QtWidgets.QHBoxLayout(self.cardProduct)
        self.horizontalLayout_card2.setObjectName("horizontalLayout_card2")
        self.verticalLayout_card2_text = QtWidgets.QVBoxLayout()
        self.verticalLayout_card2_text.setObjectName("verticalLayout_card2_text")
        self.lblCardProductNum = QtWidgets.QLabel(parent=self.cardProduct)
        self.lblCardProductNum.setObjectName("lblCardProductNum")
        self.verticalLayout_card2_text.addWidget(self.lblCardProductNum)
        self.lblCardProductTitle = QtWidgets.QLabel(parent=self.cardProduct)
        self.lblCardProductTitle.setObjectName("lblCardProductTitle")
        self.verticalLayout_card2_text.addWidget(self.lblCardProductTitle)
        self.horizontalLayout_card2.addLayout(self.verticalLayout_card2_text)
        self.lblCardProductIcon = QtWidgets.QLabel(parent=self.cardProduct)
        self.lblCardProductIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCardProductIcon.setObjectName("lblCardProductIcon")
        self.horizontalLayout_card2.addWidget(self.lblCardProductIcon)
        self.layoutStatsCards.addWidget(self.cardProduct)
        self.cardOrder = QtWidgets.QFrame(parent=self.pageDashboard)
        self.cardOrder.setObjectName("cardOrder")
        self.horizontalLayout_card3 = QtWidgets.QHBoxLayout(self.cardOrder)
        self.horizontalLayout_card3.setObjectName("horizontalLayout_card3")
        self.verticalLayout_card3_text = QtWidgets.QVBoxLayout()
        self.verticalLayout_card3_text.setObjectName("verticalLayout_card3_text")
        self.lblCardOrderNum = QtWidgets.QLabel(parent=self.cardOrder)
        self.lblCardOrderNum.setObjectName("lblCardOrderNum")
        self.verticalLayout_card3_text.addWidget(self.lblCardOrderNum)
        self.lblCardOrderTitle = QtWidgets.QLabel(parent=self.cardOrder)
        self.lblCardOrderTitle.setObjectName("lblCardOrderTitle")
        self.verticalLayout_card3_text.addWidget(self.lblCardOrderTitle)
        self.horizontalLayout_card3.addLayout(self.verticalLayout_card3_text)
        self.lblCardOrderIcon = QtWidgets.QLabel(parent=self.cardOrder)
        self.lblCardOrderIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCardOrderIcon.setObjectName("lblCardOrderIcon")
        self.horizontalLayout_card3.addWidget(self.lblCardOrderIcon)
        self.layoutStatsCards.addWidget(self.cardOrder)
        self.cardRevenue = QtWidgets.QFrame(parent=self.pageDashboard)
        self.cardRevenue.setObjectName("cardRevenue")
        self.horizontalLayout_card4 = QtWidgets.QHBoxLayout(self.cardRevenue)
        self.horizontalLayout_card4.setObjectName("horizontalLayout_card4")
        self.verticalLayout_card4_text = QtWidgets.QVBoxLayout()
        self.verticalLayout_card4_text.setObjectName("verticalLayout_card4_text")
        self.lblCardRevenueNum = QtWidgets.QLabel(parent=self.cardRevenue)
        self.lblCardRevenueNum.setObjectName("lblCardRevenueNum")
        self.verticalLayout_card4_text.addWidget(self.lblCardRevenueNum)
        self.lblCardRevenueTitle = QtWidgets.QLabel(parent=self.cardRevenue)
        self.lblCardRevenueTitle.setObjectName("lblCardRevenueTitle")
        self.verticalLayout_card4_text.addWidget(self.lblCardRevenueTitle)
        self.horizontalLayout_card4.addLayout(self.verticalLayout_card4_text)
        self.lblCardRevenueIcon = QtWidgets.QLabel(parent=self.cardRevenue)
        self.lblCardRevenueIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCardRevenueIcon.setObjectName("lblCardRevenueIcon")
        self.horizontalLayout_card4.addWidget(self.lblCardRevenueIcon)
        self.layoutStatsCards.addWidget(self.cardRevenue)
        self.cardVoucher = QtWidgets.QFrame(parent=self.pageDashboard)
        self.cardVoucher.setObjectName("cardVoucher")
        self.horizontalLayout_card5 = QtWidgets.QHBoxLayout(self.cardVoucher)
        self.horizontalLayout_card5.setObjectName("horizontalLayout_card5")
        self.verticalLayout_card5_text = QtWidgets.QVBoxLayout()
        self.verticalLayout_card5_text.setObjectName("verticalLayout_card5_text")
        self.lblCardVoucherNum = QtWidgets.QLabel(parent=self.cardVoucher)
        self.lblCardVoucherNum.setObjectName("lblCardVoucherNum")
        self.verticalLayout_card5_text.addWidget(self.lblCardVoucherNum)
        self.lblCardVoucherTitle = QtWidgets.QLabel(parent=self.cardVoucher)
        self.lblCardVoucherTitle.setObjectName("lblCardVoucherTitle")
        self.verticalLayout_card5_text.addWidget(self.lblCardVoucherTitle)
        self.horizontalLayout_card5.addLayout(self.verticalLayout_card5_text)
        self.lblCardVoucherIcon = QtWidgets.QLabel(parent=self.cardVoucher)
        self.lblCardVoucherIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCardVoucherIcon.setObjectName("lblCardVoucherIcon")
        self.horizontalLayout_card5.addWidget(self.lblCardVoucherIcon)
        self.layoutStatsCards.addWidget(self.cardVoucher)
        self.verticalLayout_page.addLayout(self.layoutStatsCards)
        self.layoutCharts = QtWidgets.QHBoxLayout()
        self.layoutCharts.setSpacing(20)
        self.layoutCharts.setObjectName("layoutCharts")
        self.frameRevenueChart = QtWidgets.QFrame(parent=self.pageDashboard)
        self.frameRevenueChart.setStyleSheet("\n"
"                #frameRevenueChart {\n"
"                    background-color: #ffffff;\n"
"                    border: 1px solid #e2e8f0;\n"
"                    border-radius: 12px;\n"
"                }\n"
"               ")
        self.frameRevenueChart.setObjectName("frameRevenueChart")
        self.verticalLayout_chart1 = QtWidgets.QVBoxLayout(self.frameRevenueChart)
        self.verticalLayout_chart1.setObjectName("verticalLayout_chart1")
        self.lblChart1Title = QtWidgets.QLabel(parent=self.frameRevenueChart)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblChart1Title.setFont(font)
        self.lblChart1Title.setObjectName("lblChart1Title")
        self.verticalLayout_chart1.addWidget(self.lblChart1Title)
        self.lblChart1Placeholder = QtWidgets.QLabel(parent=self.frameRevenueChart)
        self.lblChart1Placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblChart1Placeholder.setStyleSheet("color: #94a3b8; font-size: 11px;")
        self.lblChart1Placeholder.setObjectName("lblChart1Placeholder")
        self.verticalLayout_chart1.addWidget(self.lblChart1Placeholder)
        self.layoutCharts.addWidget(self.frameRevenueChart)
        self.frameOrderChart = QtWidgets.QFrame(parent=self.pageDashboard)
        self.frameOrderChart.setStyleSheet("\n"
"                #frameOrderChart {\n"
"                    background-color: #ffffff;\n"
"                    border: 1px solid #e2e8f0;\n"
"                    border-radius: 12px;\n"
"                }\n"
"               ")
        self.frameOrderChart.setObjectName("frameOrderChart")
        self.verticalLayout_chart2 = QtWidgets.QVBoxLayout(self.frameOrderChart)
        self.verticalLayout_chart2.setObjectName("verticalLayout_chart2")
        self.lblChart2Title = QtWidgets.QLabel(parent=self.frameOrderChart)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblChart2Title.setFont(font)
        self.lblChart2Title.setObjectName("lblChart2Title")
        self.verticalLayout_chart2.addWidget(self.lblChart2Title)
        self.lblChart2Placeholder = QtWidgets.QLabel(parent=self.frameOrderChart)
        self.lblChart2Placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblChart2Placeholder.setStyleSheet("color: #94a3b8; font-size: 11px;")
        self.lblChart2Placeholder.setObjectName("lblChart2Placeholder")
        self.verticalLayout_chart2.addWidget(self.lblChart2Placeholder)
        self.layoutCharts.addWidget(self.frameOrderChart)
        self.verticalLayout_page.addLayout(self.layoutCharts)
        self.layoutTables = QtWidgets.QHBoxLayout()
        self.layoutTables.setSpacing(20)
        self.layoutTables.setObjectName("layoutTables")
        self.verticalLayout_table1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_table1.setObjectName("verticalLayout_table1")
        self.lblTable1Header = QtWidgets.QLabel(parent=self.pageDashboard)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTable1Header.setFont(font)
        self.lblTable1Header.setObjectName("lblTable1Header")
        self.verticalLayout_table1.addWidget(self.lblTable1Header)
        self.tblTopProducts = QtWidgets.QTableWidget(parent=self.pageDashboard)
        self.tblTopProducts.setObjectName("tblTopProducts")
        self.tblTopProducts.setColumnCount(4)
        self.tblTopProducts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTopProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTopProducts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTopProducts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTopProducts.setHorizontalHeaderItem(3, item)
        self.verticalLayout_table1.addWidget(self.tblTopProducts)
        self.layoutTables.addLayout(self.verticalLayout_table1)
        self.verticalLayout_table2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_table2.setObjectName("verticalLayout_table2")
        self.lblTable2Header = QtWidgets.QLabel(parent=self.pageDashboard)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTable2Header.setFont(font)
        self.lblTable2Header.setObjectName("lblTable2Header")
        self.verticalLayout_table2.addWidget(self.lblTable2Header)
        self.tblActiveLivestreams = QtWidgets.QTableWidget(parent=self.pageDashboard)
        self.tblActiveLivestreams.setObjectName("tblActiveLivestreams")
        self.tblActiveLivestreams.setColumnCount(4)
        self.tblActiveLivestreams.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblActiveLivestreams.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblActiveLivestreams.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblActiveLivestreams.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblActiveLivestreams.setHorizontalHeaderItem(3, item)
        self.verticalLayout_table2.addWidget(self.tblActiveLivestreams)
        self.layoutTables.addLayout(self.verticalLayout_table2)
        self.verticalLayout_page.addLayout(self.layoutTables)
        self.stackedWidget.addWidget(self.pageDashboard)
        self.verticalLayout_content.addWidget(self.stackedWidget)
        self.horizontalLayout_main.addLayout(self.verticalLayout_content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LIVE SALE MANAGER - Hệ thống quản lý livestream"))
        self.lblSidebarLogo.setText(_translate("MainWindow", "🛍️"))
        self.lblSidebarTitle.setText(_translate("MainWindow", "LIVE SALE MANAGER"))
        self.lblSidebarSubtitle.setText(_translate("MainWindow", "Hệ thống Quản lý Live Stream"))
        self.btnMenuDashboard.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuDashboard.setText(_translate("MainWindow", "📊  Dashboard"))
        self.btnMenuSeller.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuSeller.setText(_translate("MainWindow", "👤  Người bán"))
        self.btnMenuCustomer.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuCustomer.setText(_translate("MainWindow", "👥  Khách hàng"))
        self.btnMenuLivestream.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuLivestream.setText(_translate("MainWindow", "🎥  Livestream"))
        self.btnMenuProduct.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuProduct.setText(_translate("MainWindow", "📦  Sản phẩm"))
        self.btnMenuLivestreamDetail.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuLivestreamDetail.setText(_translate("MainWindow", "🔍  Chi tiết Livestream"))
        self.btnMenuComment.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuComment.setText(_translate("MainWindow", "💬  Bình luận"))
        self.btnMenuOrder.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuOrder.setText(_translate("MainWindow", "🛒  Đơn hàng"))
        self.btnMenuOrderDetail.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuOrderDetail.setText(_translate("MainWindow", "📝  Chi tiết đơn hàng"))
        self.btnMenuVoucher.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuVoucher.setText(_translate("MainWindow", "🎟️  Voucher"))
        self.btnMenuPayment.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuPayment.setText(_translate("MainWindow", "💳  Thanh toán"))
        self.btnMenuStatistics.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuStatistics.setText(_translate("MainWindow", "📈  Thống kê"))
        self.btnMenuLogout.setProperty("class", _translate("MainWindow", "menu-btn"))
        self.btnMenuLogout.setText(_translate("MainWindow", "🚪  Đăng xuất"))
        self.lblHeaderTitle.setText(_translate("MainWindow", "Tổng quan Dashboard"))
        self.lblUserScope.setText(_translate("MainWindow", "Xin chào, Administrator (Admin)"))
        self.cardCustomer.setProperty("class", _translate("MainWindow", "stats-card"))
        self.lblCardCustomerNum.setProperty("class", _translate("MainWindow", "card-num"))
        self.lblCardCustomerNum.setText(_translate("MainWindow", "0"))
        self.lblCardCustomerTitle.setProperty("class", _translate("MainWindow", "card-title"))
        self.lblCardCustomerTitle.setText(_translate("MainWindow", "Tổng khách hàng"))
        self.lblCardCustomerIcon.setProperty("class", _translate("MainWindow", "card-icon"))
        self.lblCardCustomerIcon.setText(_translate("MainWindow", "👥"))
        self.cardLivestream.setProperty("class", _translate("MainWindow", "stats-card"))
        self.lblCardLivestreamNum.setProperty("class", _translate("MainWindow", "card-num"))
        self.lblCardLivestreamNum.setText(_translate("MainWindow", "12"))
        self.lblCardLivestreamTitle.setProperty("class", _translate("MainWindow", "card-title"))
        self.lblCardLivestreamTitle.setText(_translate("MainWindow", "Tổng Livestream"))
        self.lblCardLivestreamIcon.setProperty("class", _translate("MainWindow", "card-icon"))
        self.lblCardLivestreamIcon.setText(_translate("MainWindow", "🎥"))
        self.cardProduct.setProperty("class", _translate("MainWindow", "stats-card"))
        self.lblCardProductNum.setProperty("class", _translate("MainWindow", "card-num"))
        self.lblCardProductNum.setText(_translate("MainWindow", "245"))
        self.lblCardProductTitle.setProperty("class", _translate("MainWindow", "card-title"))
        self.lblCardProductTitle.setText(_translate("MainWindow", "Tổng sản phẩm"))
        self.lblCardProductIcon.setProperty("class", _translate("MainWindow", "card-icon"))
        self.lblCardProductIcon.setText(_translate("MainWindow", "📦"))
        self.cardOrder.setProperty("class", _translate("MainWindow", "stats-card"))
        self.lblCardOrderNum.setProperty("class", _translate("MainWindow", "card-num"))
        self.lblCardOrderNum.setText(_translate("MainWindow", "1,840"))
        self.lblCardOrderTitle.setProperty("class", _translate("MainWindow", "card-title"))
        self.lblCardOrderTitle.setText(_translate("MainWindow", "Tổng đơn hàng"))
        self.lblCardOrderIcon.setProperty("class", _translate("MainWindow", "card-icon"))
        self.lblCardOrderIcon.setText(_translate("MainWindow", "🛒"))
        self.cardRevenue.setProperty("class", _translate("MainWindow", "stats-card"))
        self.lblCardRevenueNum.setProperty("class", _translate("MainWindow", "card-num"))
        self.lblCardRevenueNum.setText(_translate("MainWindow", "152.8M"))
        self.lblCardRevenueTitle.setProperty("class", _translate("MainWindow", "card-title"))
        self.lblCardRevenueTitle.setText(_translate("MainWindow", "Doanh thu (VND)"))
        self.lblCardRevenueIcon.setProperty("class", _translate("MainWindow", "card-icon"))
        self.lblCardRevenueIcon.setText(_translate("MainWindow", "💰"))
        self.cardVoucher.setProperty("class", _translate("MainWindow", "stats-card"))
        self.lblCardVoucherNum.setProperty("class", _translate("MainWindow", "card-num"))
        self.lblCardVoucherNum.setText(_translate("MainWindow", "8"))
        self.lblCardVoucherTitle.setProperty("class", _translate("MainWindow", "card-title"))
        self.lblCardVoucherTitle.setText(_translate("MainWindow", "Voucher hoạt động"))
        self.lblCardVoucherIcon.setProperty("class", _translate("MainWindow", "card-icon"))
        self.lblCardVoucherIcon.setText(_translate("MainWindow", "🎟️"))
        self.lblChart1Title.setText(_translate("MainWindow", "📈 Thống kê Doanh thu (VND)"))
        self.lblChart1Placeholder.setText(_translate("MainWindow", "[Biểu đồ doanh thu - QChart hoặc Ảnh minh họa thống kê doanh thu theo thời gian]"))
        self.lblChart2Title.setText(_translate("MainWindow", "📊 Thống kê Số đơn hàng"))
        self.lblChart2Placeholder.setText(_translate("MainWindow", "[Biểu đồ đơn hàng - QChart hoặc Ảnh thống kê lượng đơn]"))
        self.lblTable1Header.setText(_translate("MainWindow", "🔥 Top sản phẩm bán chạy nhất"))
        item = self.tblTopProducts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã SP"))
        item = self.tblTopProducts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên sản phẩm"))
        item = self.tblTopProducts.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Giá bán (VND)"))
        item = self.tblTopProducts.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Đã bán"))
        self.lblTable2Header.setText(_translate("MainWindow", "🔴 Livestream đang diễn ra"))
        item = self.tblActiveLivestreams.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã Live"))
        item = self.tblActiveLivestreams.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tiêu đề Live"))
        item = self.tblActiveLivestreams.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Người bán/KOL"))
        item = self.tblActiveLivestreams.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Trạng thái"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
