# Form implementation generated from reading ui file 'LivestreamDetail.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LivestreamDetailWidget(object):
    def setupUi(self, LivestreamDetailWidget):
        LivestreamDetailWidget.setObjectName("LivestreamDetailWidget")
        LivestreamDetailWidget.resize(900, 600)
        LivestreamDetailWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 12px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit, QComboBox, QSpinBox {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 8px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus, QSpinBox:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 13px;\n"
"        padding: 8px 15px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSearch, QPushButton#btnLuu {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSearch:hover, QPushButton#btnLuu:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnThem {\n"
"        background-color: #10b981;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnThem:hover {\n"
"        background-color: #059669;\n"
"    }\n"
"    QPushButton#btnSua {\n"
"        background-color: #f59e0b;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSua:hover {\n"
"        background-color: #d97706;\n"
"    }\n"
"    QPushButton#btnXoa {\n"
"        background-color: #ef4444;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnXoa:hover {\n"
"        background-color: #dc2626;\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnHuy, QPushButton#btnXuatExcel {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnHuy:hover, QPushButton#btnXuatExcel:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 8px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(LivestreamDetailWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=LivestreamDetailWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=LivestreamDetailWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=LivestreamDetailWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutSearch = QtWidgets.QHBoxLayout()
        self.layoutSearch.setSpacing(6)
        self.layoutSearch.setObjectName("layoutSearch")
        self.txtSearch = QtWidgets.QLineEdit(parent=LivestreamDetailWidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.layoutSearch.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=LivestreamDetailWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.layoutSearch.addWidget(self.btnSearch)
        self.btnRefresh = QtWidgets.QPushButton(parent=LivestreamDetailWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutSearch.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutSearch)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutBody = QtWidgets.QHBoxLayout()
        self.layoutBody.setSpacing(15)
        self.layoutBody.setObjectName("layoutBody")
        self.grpLivestreamDetailForm = QtWidgets.QGroupBox(parent=LivestreamDetailWidget)
        self.grpLivestreamDetailForm.setMinimumSize(QtCore.QSize(320, 0))
        self.grpLivestreamDetailForm.setMaximumSize(QtCore.QSize(350, 16777215))
        self.grpLivestreamDetailForm.setObjectName("grpLivestreamDetailForm")
        self.verticalLayout_form = QtWidgets.QVBoxLayout(self.grpLivestreamDetailForm)
        self.verticalLayout_form.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_form.setSpacing(12)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.verticalLayout_live = QtWidgets.QVBoxLayout()
        self.verticalLayout_live.setSpacing(4)
        self.verticalLayout_live.setObjectName("verticalLayout_live")
        self.lblLivestream = QtWidgets.QLabel(parent=self.grpLivestreamDetailForm)
        self.lblLivestream.setObjectName("lblLivestream")
        self.verticalLayout_live.addWidget(self.lblLivestream)
        self.cbLivestream = QtWidgets.QComboBox(parent=self.grpLivestreamDetailForm)
        self.cbLivestream.setObjectName("cbLivestream")
        self.verticalLayout_live.addWidget(self.cbLivestream)
        self.verticalLayout_form.addLayout(self.verticalLayout_live)
        self.verticalLayout_product = QtWidgets.QVBoxLayout()
        self.verticalLayout_product.setSpacing(4)
        self.verticalLayout_product.setObjectName("verticalLayout_product")
        self.lblSanPham = QtWidgets.QLabel(parent=self.grpLivestreamDetailForm)
        self.lblSanPham.setObjectName("lblSanPham")
        self.verticalLayout_product.addWidget(self.lblSanPham)
        self.cbSanPham = QtWidgets.QComboBox(parent=self.grpLivestreamDetailForm)
        self.cbSanPham.setObjectName("cbSanPham")
        self.verticalLayout_product.addWidget(self.cbSanPham)
        self.verticalLayout_form.addLayout(self.verticalLayout_product)
        self.verticalLayout_qty = QtWidgets.QVBoxLayout()
        self.verticalLayout_qty.setSpacing(4)
        self.verticalLayout_qty.setObjectName("verticalLayout_qty")
        self.lblSoLuongGioiThieu = QtWidgets.QLabel(parent=self.grpLivestreamDetailForm)
        self.lblSoLuongGioiThieu.setObjectName("lblSoLuongGioiThieu")
        self.verticalLayout_qty.addWidget(self.lblSoLuongGioiThieu)
        self.spinSoLuongGioiThieu = QtWidgets.QSpinBox(parent=self.grpLivestreamDetailForm)
        self.spinSoLuongGioiThieu.setMaximum(9999)
        self.spinSoLuongGioiThieu.setObjectName("spinSoLuongGioiThieu")
        self.verticalLayout_qty.addWidget(self.spinSoLuongGioiThieu)
        self.verticalLayout_form.addLayout(self.verticalLayout_qty)
        self.verticalLayout_promo_price = QtWidgets.QVBoxLayout()
        self.verticalLayout_promo_price.setSpacing(4)
        self.verticalLayout_promo_price.setObjectName("verticalLayout_promo_price")
        self.lblGiaKhuyenMai = QtWidgets.QLabel(parent=self.grpLivestreamDetailForm)
        self.lblGiaKhuyenMai.setObjectName("lblGiaKhuyenMai")
        self.verticalLayout_promo_price.addWidget(self.lblGiaKhuyenMai)
        self.txtGiaKhuyenMai = QtWidgets.QLineEdit(parent=self.grpLivestreamDetailForm)
        self.txtGiaKhuyenMai.setObjectName("txtGiaKhuyenMai")
        self.verticalLayout_promo_price.addWidget(self.txtGiaKhuyenMai)
        self.verticalLayout_form.addLayout(self.verticalLayout_promo_price)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_form.addItem(spacerItem1)
        self.layoutBody.addWidget(self.grpLivestreamDetailForm)
        self.tblLivestreamDetail = QtWidgets.QTableWidget(parent=LivestreamDetailWidget)
        self.tblLivestreamDetail.setObjectName("tblLivestreamDetail")
        self.tblLivestreamDetail.setColumnCount(6)
        self.tblLivestreamDetail.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestreamDetail.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestreamDetail.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestreamDetail.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestreamDetail.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestreamDetail.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestreamDetail.setHorizontalHeaderItem(5, item)
        self.layoutBody.addWidget(self.tblLivestreamDetail)
        self.verticalLayout_main.addLayout(self.layoutBody)
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setSpacing(10)
        self.layoutActions.setObjectName("layoutActions")
        self.btnThem = QtWidgets.QPushButton(parent=LivestreamDetailWidget)
        self.btnThem.setObjectName("btnThem")
        self.layoutActions.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=LivestreamDetailWidget)
        self.btnSua.setObjectName("btnSua")
        self.layoutActions.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=LivestreamDetailWidget)
        self.btnXoa.setObjectName("btnXoa")
        self.layoutActions.addWidget(self.btnXoa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutActions.addItem(spacerItem2)
        self.btnLuu = QtWidgets.QPushButton(parent=LivestreamDetailWidget)
        self.btnLuu.setObjectName("btnLuu")
        self.layoutActions.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=LivestreamDetailWidget)
        self.btnHuy.setObjectName("btnHuy")
        self.layoutActions.addWidget(self.btnHuy)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=LivestreamDetailWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutActions)
        self.lblStatus = QtWidgets.QLabel(parent=LivestreamDetailWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(LivestreamDetailWidget)
        QtCore.QMetaObject.connectSlotsByName(LivestreamDetailWidget)

    def retranslateUi(self, LivestreamDetailWidget):
        _translate = QtCore.QCoreApplication.translate
        LivestreamDetailWidget.setWindowTitle(_translate("LivestreamDetailWidget", "Chi tiết sản phẩm Livestream"))
        self.lblIconBadge.setText(_translate("LivestreamDetailWidget", "🔍"))
        self.lblTitle.setText(_translate("LivestreamDetailWidget", "CHI TIẾT DIỄN BIẾN LIVESTREAM (PRODUCTS IN STREAM)"))
        self.lblSubtitle.setText(_translate("LivestreamDetailWidget", "Quản lý các sản phẩm được giới thiệu, số lượng giới thiệu và đơn giá khuyến mãi đặc biệt trong livestream"))
        self.txtSearch.setPlaceholderText(_translate("LivestreamDetailWidget", "Tìm kiếm theo mã live hoặc SP..."))
        self.btnSearch.setText(_translate("LivestreamDetailWidget", "🔍 Tìm kiếm"))
        self.btnRefresh.setText(_translate("LivestreamDetailWidget", "🔄 Làm mới"))
        self.grpLivestreamDetailForm.setTitle(_translate("LivestreamDetailWidget", "Thông tin chi tiết giới thiệu"))
        self.lblLivestream.setText(_translate("LivestreamDetailWidget", "Buổi Livestream:"))
        self.lblSanPham.setText(_translate("LivestreamDetailWidget", "Sản phẩm giới thiệu:"))
        self.lblSoLuongGioiThieu.setText(_translate("LivestreamDetailWidget", "Số lượng giới thiệu:"))
        self.lblGiaKhuyenMai.setText(_translate("LivestreamDetailWidget", "Giá khuyến mãi (VND):"))
        item = self.tblLivestreamDetail.horizontalHeaderItem(0)
        item.setText(_translate("LivestreamDetailWidget", "Mã Chi Tiết Live"))
        item = self.tblLivestreamDetail.horizontalHeaderItem(1)
        item.setText(_translate("LivestreamDetailWidget", "Tiêu Đề Livestream"))
        item = self.tblLivestreamDetail.horizontalHeaderItem(2)
        item.setText(_translate("LivestreamDetailWidget", "Mã Sản Phẩm"))
        item = self.tblLivestreamDetail.horizontalHeaderItem(3)
        item.setText(_translate("LivestreamDetailWidget", "Tên Sản Phẩm"))
        item = self.tblLivestreamDetail.horizontalHeaderItem(4)
        item.setText(_translate("LivestreamDetailWidget", "SL Giới Thiệu"))
        item = self.tblLivestreamDetail.horizontalHeaderItem(5)
        item.setText(_translate("LivestreamDetailWidget", "Giá Khuyến Mãi (VND)"))
        self.btnThem.setText(_translate("LivestreamDetailWidget", "➕ Thêm mới"))
        self.btnSua.setText(_translate("LivestreamDetailWidget", "✏️ Sửa đổi"))
        self.btnXoa.setText(_translate("LivestreamDetailWidget", "🗑️ Xóa bỏ"))
        self.btnLuu.setText(_translate("LivestreamDetailWidget", "💾 Lưu lại"))
        self.btnHuy.setText(_translate("LivestreamDetailWidget", "❌ Hủy bỏ"))
        self.btnXuatExcel.setText(_translate("LivestreamDetailWidget", "📥 Xuất Excel"))
        self.lblStatus.setText(_translate("LivestreamDetailWidget", "Trạng thái: Sẵn sàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LivestreamDetailWidget = QtWidgets.QWidget()
    ui = Ui_LivestreamDetailWidget()
    ui.setupUi(LivestreamDetailWidget)
    LivestreamDetailWidget.show()
    sys.exit(app.exec())
