# Form implementation generated from reading ui file 'Comment.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CommentWidget(object):
    def setupUi(self, CommentWidget):
        CommentWidget.setObjectName("CommentWidget")
        CommentWidget.resize(900, 600)
        CommentWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 12px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit, QComboBox, QDateTimeEdit {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 8px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus, QDateTimeEdit:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 13px;\n"
"        padding: 8px 15px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSearch, QPushButton#btnLuu {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSearch:hover, QPushButton#btnLuu:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnThem {\n"
"        background-color: #10b981;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnThem:hover {\n"
"        background-color: #059669;\n"
"    }\n"
"    QPushButton#btnSua {\n"
"        background-color: #f59e0b;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSua:hover {\n"
"        background-color: #d97706;\n"
"    }\n"
"    QPushButton#btnXoa {\n"
"        background-color: #ef4444;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnXoa:hover {\n"
"        background-color: #dc2626;\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnHuy, QPushButton#btnXuatExcel {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnHuy:hover, QPushButton#btnXuatExcel:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 8px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(CommentWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=CommentWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=CommentWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=CommentWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutSearch = QtWidgets.QHBoxLayout()
        self.layoutSearch.setSpacing(6)
        self.layoutSearch.setObjectName("layoutSearch")
        self.txtSearch = QtWidgets.QLineEdit(parent=CommentWidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.layoutSearch.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=CommentWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.layoutSearch.addWidget(self.btnSearch)
        self.btnRefresh = QtWidgets.QPushButton(parent=CommentWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutSearch.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutSearch)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutBody = QtWidgets.QHBoxLayout()
        self.layoutBody.setSpacing(15)
        self.layoutBody.setObjectName("layoutBody")
        self.grpCommentForm = QtWidgets.QGroupBox(parent=CommentWidget)
        self.grpCommentForm.setMinimumSize(QtCore.QSize(320, 0))
        self.grpCommentForm.setMaximumSize(QtCore.QSize(350, 16777215))
        self.grpCommentForm.setObjectName("grpCommentForm")
        self.verticalLayout_form = QtWidgets.QVBoxLayout(self.grpCommentForm)
        self.verticalLayout_form.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_form.setSpacing(12)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.verticalLayout_live = QtWidgets.QVBoxLayout()
        self.verticalLayout_live.setSpacing(4)
        self.verticalLayout_live.setObjectName("verticalLayout_live")
        self.lblLivestream = QtWidgets.QLabel(parent=self.grpCommentForm)
        self.lblLivestream.setObjectName("lblLivestream")
        self.verticalLayout_live.addWidget(self.lblLivestream)
        self.cbLivestream = QtWidgets.QComboBox(parent=self.grpCommentForm)
        self.cbLivestream.setObjectName("cbLivestream")
        self.verticalLayout_live.addWidget(self.cbLivestream)
        self.verticalLayout_form.addLayout(self.verticalLayout_live)
        self.verticalLayout_user = QtWidgets.QVBoxLayout()
        self.verticalLayout_user.setSpacing(4)
        self.verticalLayout_user.setObjectName("verticalLayout_user")
        self.lblTenNguoiDung = QtWidgets.QLabel(parent=self.grpCommentForm)
        self.lblTenNguoiDung.setObjectName("lblTenNguoiDung")
        self.verticalLayout_user.addWidget(self.lblTenNguoiDung)
        self.txtTenNguoiDung = QtWidgets.QLineEdit(parent=self.grpCommentForm)
        self.txtTenNguoiDung.setObjectName("txtTenNguoiDung")
        self.verticalLayout_user.addWidget(self.txtTenNguoiDung)
        self.verticalLayout_form.addLayout(self.verticalLayout_user)
        self.verticalLayout_content = QtWidgets.QVBoxLayout()
        self.verticalLayout_content.setSpacing(4)
        self.verticalLayout_content.setObjectName("verticalLayout_content")
        self.lblNoiDung = QtWidgets.QLabel(parent=self.grpCommentForm)
        self.lblNoiDung.setObjectName("lblNoiDung")
        self.verticalLayout_content.addWidget(self.lblNoiDung)
        self.txtNoiDung = QtWidgets.QLineEdit(parent=self.grpCommentForm)
        self.txtNoiDung.setObjectName("txtNoiDung")
        self.verticalLayout_content.addWidget(self.txtNoiDung)
        self.verticalLayout_form.addLayout(self.verticalLayout_content)
        self.verticalLayout_time = QtWidgets.QVBoxLayout()
        self.verticalLayout_time.setSpacing(4)
        self.verticalLayout_time.setObjectName("verticalLayout_time")
        self.lblThoiGian = QtWidgets.QLabel(parent=self.grpCommentForm)
        self.lblThoiGian.setObjectName("lblThoiGian")
        self.verticalLayout_time.addWidget(self.lblThoiGian)
        self.dateThoiGian = QtWidgets.QDateTimeEdit(parent=self.grpCommentForm)
        self.dateThoiGian.setCalendarPopup(True)
        self.dateThoiGian.setObjectName("dateThoiGian")
        self.verticalLayout_time.addWidget(self.dateThoiGian)
        self.verticalLayout_form.addLayout(self.verticalLayout_time)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_form.addItem(spacerItem1)
        self.layoutBody.addWidget(self.grpCommentForm)
        self.tblComment = QtWidgets.QTableWidget(parent=CommentWidget)
        self.tblComment.setObjectName("tblComment")
        self.tblComment.setColumnCount(5)
        self.tblComment.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblComment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblComment.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblComment.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblComment.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblComment.setHorizontalHeaderItem(4, item)
        self.layoutBody.addWidget(self.tblComment)
        self.verticalLayout_main.addLayout(self.layoutBody)
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setSpacing(10)
        self.layoutActions.setObjectName("layoutActions")
        self.btnThem = QtWidgets.QPushButton(parent=CommentWidget)
        self.btnThem.setObjectName("btnThem")
        self.layoutActions.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=CommentWidget)
        self.btnSua.setObjectName("btnSua")
        self.layoutActions.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=CommentWidget)
        self.btnXoa.setObjectName("btnXoa")
        self.layoutActions.addWidget(self.btnXoa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutActions.addItem(spacerItem2)
        self.btnLuu = QtWidgets.QPushButton(parent=CommentWidget)
        self.btnLuu.setObjectName("btnLuu")
        self.layoutActions.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=CommentWidget)
        self.btnHuy.setObjectName("btnHuy")
        self.layoutActions.addWidget(self.btnHuy)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=CommentWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutActions)
        self.lblStatus = QtWidgets.QLabel(parent=CommentWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(CommentWidget)
        QtCore.QMetaObject.connectSlotsByName(CommentWidget)

    def retranslateUi(self, CommentWidget):
        _translate = QtCore.QCoreApplication.translate
        CommentWidget.setWindowTitle(_translate("CommentWidget", "Quản lý Bình luận Livestream"))
        self.lblIconBadge.setText(_translate("CommentWidget", "💬"))
        self.lblTitle.setText(_translate("CommentWidget", "QUẢN LÝ BÌNH LUẬN (COMMENT)"))
        self.lblSubtitle.setText(_translate("CommentWidget", "Xem và kiểm duyệt bình luận của người dùng tương tác trong suốt livestream"))
        self.txtSearch.setPlaceholderText(_translate("CommentWidget", "Tìm tên người dùng, nội dung..."))
        self.btnSearch.setText(_translate("CommentWidget", "🔍 Tìm kiếm"))
        self.btnRefresh.setText(_translate("CommentWidget", "🔄 Làm mới"))
        self.grpCommentForm.setTitle(_translate("CommentWidget", "Thông tin bình luận"))
        self.lblLivestream.setText(_translate("CommentWidget", "Buổi Livestream:"))
        self.lblTenNguoiDung.setText(_translate("CommentWidget", "Tên khách hàng:"))
        self.lblNoiDung.setText(_translate("CommentWidget", "Nội dung bình luận:"))
        self.lblThoiGian.setText(_translate("CommentWidget", "Thời gian gửi:"))
        item = self.tblComment.horizontalHeaderItem(0)
        item.setText(_translate("CommentWidget", "Mã Bình Luận"))
        item = self.tblComment.horizontalHeaderItem(1)
        item.setText(_translate("CommentWidget", "Livestream"))
        item = self.tblComment.horizontalHeaderItem(2)
        item.setText(_translate("CommentWidget", "Tên Khách Hàng"))
        item = self.tblComment.horizontalHeaderItem(3)
        item.setText(_translate("CommentWidget", "Nội Dung Bình Luận"))
        item = self.tblComment.horizontalHeaderItem(4)
        item.setText(_translate("CommentWidget", "Thời Gian Gửi"))
        self.btnThem.setText(_translate("CommentWidget", "➕ Thêm mới"))
        self.btnSua.setText(_translate("CommentWidget", "✏️ Sửa đổi"))
        self.btnXoa.setText(_translate("CommentWidget", "🗑️ Xóa bỏ"))
        self.btnLuu.setText(_translate("CommentWidget", "💾 Lưu lại"))
        self.btnHuy.setText(_translate("CommentWidget", "❌ Hủy bỏ"))
        self.btnXuatExcel.setText(_translate("CommentWidget", "📥 Xuất Excel"))
        self.lblStatus.setText(_translate("CommentWidget", "Trạng thái: Sẵn sàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CommentWidget = QtWidgets.QWidget()
    ui = Ui_CommentWidget()
    ui.setupUi(CommentWidget)
    CommentWidget.show()
    sys.exit(app.exec())
