# Form implementation generated from reading ui file 'Product.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProductWidget(object):
    def setupUi(self, ProductWidget):
        ProductWidget.setObjectName("ProductWidget")
        ProductWidget.resize(900, 600)
        ProductWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 12px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit, QComboBox, QSpinBox {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 8px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus, QSpinBox:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 13px;\n"
"        padding: 8px 15px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSearch, QPushButton#btnLuu {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSearch:hover, QPushButton#btnLuu:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnThem {\n"
"        background-color: #10b981;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnThem:hover {\n"
"        background-color: #059669;\n"
"    }\n"
"    QPushButton#btnSua {\n"
"        background-color: #f59e0b;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSua:hover {\n"
"        background-color: #d97706;\n"
"    }\n"
"    QPushButton#btnXoa {\n"
"        background-color: #ef4444;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnXoa:hover {\n"
"        background-color: #dc2626;\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnHuy, QPushButton#btnXuatExcel, QPushButton#btnSelectImage {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnHuy:hover, QPushButton#btnXuatExcel:hover, QPushButton#btnSelectImage:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QLabel#lblImagePreview {\n"
"        border: 1px dashed #cbd5e1;\n"
"        border-radius: 8px;\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        color: #94a3b8;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 8px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(ProductWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=ProductWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=ProductWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=ProductWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutSearch = QtWidgets.QHBoxLayout()
        self.layoutSearch.setSpacing(6)
        self.layoutSearch.setObjectName("layoutSearch")
        self.txtSearch = QtWidgets.QLineEdit(parent=ProductWidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.layoutSearch.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=ProductWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.layoutSearch.addWidget(self.btnSearch)
        self.btnRefresh = QtWidgets.QPushButton(parent=ProductWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutSearch.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutSearch)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutBody = QtWidgets.QHBoxLayout()
        self.layoutBody.setSpacing(15)
        self.layoutBody.setObjectName("layoutBody")
        self.grpProductForm = QtWidgets.QGroupBox(parent=ProductWidget)
        self.grpProductForm.setMinimumSize(QtCore.QSize(320, 0))
        self.grpProductForm.setMaximumSize(QtCore.QSize(350, 16777215))
        self.grpProductForm.setObjectName("grpProductForm")
        self.verticalLayout_form = QtWidgets.QVBoxLayout(self.grpProductForm)
        self.verticalLayout_form.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_form.setSpacing(10)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.verticalLayout_name = QtWidgets.QVBoxLayout()
        self.verticalLayout_name.setSpacing(4)
        self.verticalLayout_name.setObjectName("verticalLayout_name")
        self.lblTenSP = QtWidgets.QLabel(parent=self.grpProductForm)
        self.lblTenSP.setObjectName("lblTenSP")
        self.verticalLayout_name.addWidget(self.lblTenSP)
        self.txtTenSP = QtWidgets.QLineEdit(parent=self.grpProductForm)
        self.txtTenSP.setObjectName("txtTenSP")
        self.verticalLayout_name.addWidget(self.txtTenSP)
        self.verticalLayout_form.addLayout(self.verticalLayout_name)
        self.verticalLayout_price = QtWidgets.QVBoxLayout()
        self.verticalLayout_price.setSpacing(4)
        self.verticalLayout_price.setObjectName("verticalLayout_price")
        self.lblGiaBan = QtWidgets.QLabel(parent=self.grpProductForm)
        self.lblGiaBan.setObjectName("lblGiaBan")
        self.verticalLayout_price.addWidget(self.lblGiaBan)
        self.txtGiaBan = QtWidgets.QLineEdit(parent=self.grpProductForm)
        self.txtGiaBan.setObjectName("txtGiaBan")
        self.verticalLayout_price.addWidget(self.txtGiaBan)
        self.verticalLayout_form.addLayout(self.verticalLayout_price)
        self.horizontalLayout_stock_status = QtWidgets.QHBoxLayout()
        self.horizontalLayout_stock_status.setSpacing(10)
        self.horizontalLayout_stock_status.setObjectName("horizontalLayout_stock_status")
        self.verticalLayout_stock = QtWidgets.QVBoxLayout()
        self.verticalLayout_stock.setSpacing(4)
        self.verticalLayout_stock.setObjectName("verticalLayout_stock")
        self.lblSoLuongTon = QtWidgets.QLabel(parent=self.grpProductForm)
        self.lblSoLuongTon.setObjectName("lblSoLuongTon")
        self.verticalLayout_stock.addWidget(self.lblSoLuongTon)
        self.spinSoLuongTon = QtWidgets.QSpinBox(parent=self.grpProductForm)
        self.spinSoLuongTon.setMaximum(999999)
        self.spinSoLuongTon.setObjectName("spinSoLuongTon")
        self.verticalLayout_stock.addWidget(self.spinSoLuongTon)
        self.horizontalLayout_stock_status.addLayout(self.verticalLayout_stock)
        self.verticalLayout_status = QtWidgets.QVBoxLayout()
        self.verticalLayout_status.setSpacing(4)
        self.verticalLayout_status.setObjectName("verticalLayout_status")
        self.lblTrangThai = QtWidgets.QLabel(parent=self.grpProductForm)
        self.lblTrangThai.setObjectName("lblTrangThai")
        self.verticalLayout_status.addWidget(self.lblTrangThai)
        self.cbTrangThai = QtWidgets.QComboBox(parent=self.grpProductForm)
        self.cbTrangThai.setObjectName("cbTrangThai")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.verticalLayout_status.addWidget(self.cbTrangThai)
        self.horizontalLayout_stock_status.addLayout(self.verticalLayout_status)
        self.verticalLayout_form.addLayout(self.horizontalLayout_stock_status)
        self.verticalLayout_image = QtWidgets.QVBoxLayout()
        self.verticalLayout_image.setSpacing(4)
        self.verticalLayout_image.setObjectName("verticalLayout_image")
        self.lblImage = QtWidgets.QLabel(parent=self.grpProductForm)
        self.lblImage.setObjectName("lblImage")
        self.verticalLayout_image.addWidget(self.lblImage)
        self.horizontalLayout_image_select = QtWidgets.QHBoxLayout()
        self.horizontalLayout_image_select.setSpacing(6)
        self.horizontalLayout_image_select.setObjectName("horizontalLayout_image_select")
        self.txtImagePath = QtWidgets.QLineEdit(parent=self.grpProductForm)
        self.txtImagePath.setReadOnly(True)
        self.txtImagePath.setObjectName("txtImagePath")
        self.horizontalLayout_image_select.addWidget(self.txtImagePath)
        self.btnSelectImage = QtWidgets.QPushButton(parent=self.grpProductForm)
        self.btnSelectImage.setObjectName("btnSelectImage")
        self.horizontalLayout_image_select.addWidget(self.btnSelectImage)
        self.verticalLayout_image.addLayout(self.horizontalLayout_image_select)
        self.verticalLayout_form.addLayout(self.verticalLayout_image)
        self.lblImagePreview = QtWidgets.QLabel(parent=self.grpProductForm)
        self.lblImagePreview.setMinimumSize(QtCore.QSize(0, 120))
        self.lblImagePreview.setMaximumSize(QtCore.QSize(16777215, 120))
        self.lblImagePreview.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblImagePreview.setObjectName("lblImagePreview")
        self.verticalLayout_form.addWidget(self.lblImagePreview)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_form.addItem(spacerItem1)
        self.layoutBody.addWidget(self.grpProductForm)
        self.tblProduct = QtWidgets.QTableWidget(parent=ProductWidget)
        self.tblProduct.setObjectName("tblProduct")
        self.tblProduct.setColumnCount(6)
        self.tblProduct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProduct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProduct.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProduct.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblProduct.setHorizontalHeaderItem(5, item)
        self.layoutBody.addWidget(self.tblProduct)
        self.verticalLayout_main.addLayout(self.layoutBody)
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setSpacing(10)
        self.layoutActions.setObjectName("layoutActions")
        self.btnThem = QtWidgets.QPushButton(parent=ProductWidget)
        self.btnThem.setObjectName("btnThem")
        self.layoutActions.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=ProductWidget)
        self.btnSua.setObjectName("btnSua")
        self.layoutActions.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=ProductWidget)
        self.btnXoa.setObjectName("btnXoa")
        self.layoutActions.addWidget(self.btnXoa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutActions.addItem(spacerItem2)
        self.btnLuu = QtWidgets.QPushButton(parent=ProductWidget)
        self.btnLuu.setObjectName("btnLuu")
        self.layoutActions.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=ProductWidget)
        self.btnHuy.setObjectName("btnHuy")
        self.layoutActions.addWidget(self.btnHuy)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=ProductWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutActions)
        self.lblStatus = QtWidgets.QLabel(parent=ProductWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(ProductWidget)
        QtCore.QMetaObject.connectSlotsByName(ProductWidget)

    def retranslateUi(self, ProductWidget):
        _translate = QtCore.QCoreApplication.translate
        ProductWidget.setWindowTitle(_translate("ProductWidget", "Quản lý Sản phẩm"))
        self.lblIconBadge.setText(_translate("ProductWidget", "📦"))
        self.lblTitle.setText(_translate("ProductWidget", "QUẢN LÝ SẢN PHẨM (PRODUCT)"))
        self.lblSubtitle.setText(_translate("ProductWidget", "Quản lý danh sách sản phẩm, giá bán, số lượng tồn kho và xem trước hình ảnh"))
        self.txtSearch.setPlaceholderText(_translate("ProductWidget", "Tìm kiếm theo tên sản phẩm..."))
        self.btnSearch.setText(_translate("ProductWidget", "🔍 Tìm kiếm"))
        self.btnRefresh.setText(_translate("ProductWidget", "🔄 Làm mới"))
        self.grpProductForm.setTitle(_translate("ProductWidget", "Thông tin sản phẩm"))
        self.lblTenSP.setText(_translate("ProductWidget", "Tên sản phẩm:"))
        self.lblGiaBan.setText(_translate("ProductWidget", "Giá bán (VND):"))
        self.lblSoLuongTon.setText(_translate("ProductWidget", "Số lượng tồn:"))
        self.lblTrangThai.setText(_translate("ProductWidget", "Trạng thái:"))
        self.cbTrangThai.setItemText(0, _translate("ProductWidget", "Còn hàng"))
        self.cbTrangThai.setItemText(1, _translate("ProductWidget", "Hết hàng"))
        self.lblImage.setText(_translate("ProductWidget", "Hình ảnh sản phẩm:"))
        self.txtImagePath.setPlaceholderText(_translate("ProductWidget", "Đường dẫn hình ảnh..."))
        self.btnSelectImage.setText(_translate("ProductWidget", "🖼️ Chọn ảnh"))
        self.lblImagePreview.setText(_translate("ProductWidget", "Xem trước hình ảnh"))
        item = self.tblProduct.horizontalHeaderItem(0)
        item.setText(_translate("ProductWidget", "Mã SP"))
        item = self.tblProduct.horizontalHeaderItem(1)
        item.setText(_translate("ProductWidget", "Tên Sản Phẩm"))
        item = self.tblProduct.horizontalHeaderItem(2)
        item.setText(_translate("ProductWidget", "Giá Bán"))
        item = self.tblProduct.horizontalHeaderItem(3)
        item.setText(_translate("ProductWidget", "Số Tồn Kho"))
        item = self.tblProduct.horizontalHeaderItem(4)
        item.setText(_translate("ProductWidget", "Đường Dẫn Ảnh"))
        item = self.tblProduct.horizontalHeaderItem(5)
        item.setText(_translate("ProductWidget", "Trạng Thái"))
        self.btnThem.setText(_translate("ProductWidget", "➕ Thêm mới"))
        self.btnSua.setText(_translate("ProductWidget", "✏️ Sửa đổi"))
        self.btnXoa.setText(_translate("ProductWidget", "🗑️ Xóa bỏ"))
        self.btnLuu.setText(_translate("ProductWidget", "💾 Lưu lại"))
        self.btnHuy.setText(_translate("ProductWidget", "❌ Hủy bỏ"))
        self.btnXuatExcel.setText(_translate("ProductWidget", "📥 Xuất Excel"))
        self.lblStatus.setText(_translate("ProductWidget", "Trạng thái: Sẵn sàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProductWidget = QtWidgets.QWidget()
    ui = Ui_ProductWidget()
    ui.setupUi(ProductWidget)
    ProductWidget.show()
    sys.exit(app.exec())
