# Form implementation generated from reading ui file 'Livestream.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LivestreamWidget(object):
    def setupUi(self, LivestreamWidget):
        LivestreamWidget.setObjectName("LivestreamWidget")
        LivestreamWidget.resize(900, 600)
        LivestreamWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 12px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit, QComboBox, QDateTimeEdit {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 8px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus, QDateTimeEdit:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 13px;\n"
"        padding: 8px 15px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSearch, QPushButton#btnLuu {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSearch:hover, QPushButton#btnLuu:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnThem {\n"
"        background-color: #10b981;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnThem:hover {\n"
"        background-color: #059669;\n"
"    }\n"
"    QPushButton#btnSua {\n"
"        background-color: #f59e0b;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSua:hover {\n"
"        background-color: #d97706;\n"
"    }\n"
"    QPushButton#btnXoa {\n"
"        background-color: #ef4444;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnXoa:hover {\n"
"        background-color: #dc2626;\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnHuy, QPushButton#btnXuatExcel {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnHuy:hover, QPushButton#btnXuatExcel:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 8px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(LivestreamWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=LivestreamWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=LivestreamWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=LivestreamWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutSearch = QtWidgets.QHBoxLayout()
        self.layoutSearch.setSpacing(6)
        self.layoutSearch.setObjectName("layoutSearch")
        self.txtSearch = QtWidgets.QLineEdit(parent=LivestreamWidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.layoutSearch.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=LivestreamWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.layoutSearch.addWidget(self.btnSearch)
        self.btnRefresh = QtWidgets.QPushButton(parent=LivestreamWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutSearch.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutSearch)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutBody = QtWidgets.QHBoxLayout()
        self.layoutBody.setSpacing(15)
        self.layoutBody.setObjectName("layoutBody")
        self.grpLivestreamForm = QtWidgets.QGroupBox(parent=LivestreamWidget)
        self.grpLivestreamForm.setMinimumSize(QtCore.QSize(320, 0))
        self.grpLivestreamForm.setMaximumSize(QtCore.QSize(350, 16777215))
        self.grpLivestreamForm.setObjectName("grpLivestreamForm")
        self.verticalLayout_form = QtWidgets.QVBoxLayout(self.grpLivestreamForm)
        self.verticalLayout_form.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_form.setSpacing(12)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.verticalLayout_tieu_de = QtWidgets.QVBoxLayout()
        self.verticalLayout_tieu_de.setSpacing(4)
        self.verticalLayout_tieu_de.setObjectName("verticalLayout_tieu_de")
        self.lblTieuDe = QtWidgets.QLabel(parent=self.grpLivestreamForm)
        self.lblTieuDe.setObjectName("lblTieuDe")
        self.verticalLayout_tieu_de.addWidget(self.lblTieuDe)
        self.txtTieuDe = QtWidgets.QLineEdit(parent=self.grpLivestreamForm)
        self.txtTieuDe.setObjectName("txtTieuDe")
        self.verticalLayout_tieu_de.addWidget(self.txtTieuDe)
        self.verticalLayout_form.addLayout(self.verticalLayout_tieu_de)
        self.verticalLayout_nguoi_ban = QtWidgets.QVBoxLayout()
        self.verticalLayout_nguoi_ban.setSpacing(4)
        self.verticalLayout_nguoi_ban.setObjectName("verticalLayout_nguoi_ban")
        self.lblNguoiBan = QtWidgets.QLabel(parent=self.grpLivestreamForm)
        self.lblNguoiBan.setObjectName("lblNguoiBan")
        self.verticalLayout_nguoi_ban.addWidget(self.lblNguoiBan)
        self.cbNguoiBan = QtWidgets.QComboBox(parent=self.grpLivestreamForm)
        self.cbNguoiBan.setObjectName("cbNguoiBan")
        self.verticalLayout_nguoi_ban.addWidget(self.cbNguoiBan)
        self.verticalLayout_form.addLayout(self.verticalLayout_nguoi_ban)
        self.verticalLayout_ngay_khai_mac = QtWidgets.QVBoxLayout()
        self.verticalLayout_ngay_khai_mac.setSpacing(4)
        self.verticalLayout_ngay_khai_mac.setObjectName("verticalLayout_ngay_khai_mac")
        self.lblNgayKhaiMac = QtWidgets.QLabel(parent=self.grpLivestreamForm)
        self.lblNgayKhaiMac.setObjectName("lblNgayKhaiMac")
        self.verticalLayout_ngay_khai_mac.addWidget(self.lblNgayKhaiMac)
        self.dateNgayKhaiMac = QtWidgets.QDateTimeEdit(parent=self.grpLivestreamForm)
        self.dateNgayKhaiMac.setCalendarPopup(True)
        self.dateNgayKhaiMac.setObjectName("dateNgayKhaiMac")
        self.verticalLayout_ngay_khai_mac.addWidget(self.dateNgayKhaiMac)
        self.verticalLayout_form.addLayout(self.verticalLayout_ngay_khai_mac)
        self.verticalLayout_trang_thai = QtWidgets.QVBoxLayout()
        self.verticalLayout_trang_thai.setSpacing(4)
        self.verticalLayout_trang_thai.setObjectName("verticalLayout_trang_thai")
        self.lblTrangThai = QtWidgets.QLabel(parent=self.grpLivestreamForm)
        self.lblTrangThai.setObjectName("lblTrangThai")
        self.verticalLayout_trang_thai.addWidget(self.lblTrangThai)
        self.cbTrangThai = QtWidgets.QComboBox(parent=self.grpLivestreamForm)
        self.cbTrangThai.setObjectName("cbTrangThai")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.cbTrangThai.addItem("")
        self.verticalLayout_trang_thai.addWidget(self.cbTrangThai)
        self.verticalLayout_form.addLayout(self.verticalLayout_trang_thai)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_form.addItem(spacerItem1)
        self.layoutBody.addWidget(self.grpLivestreamForm)
        self.tblLivestream = QtWidgets.QTableWidget(parent=LivestreamWidget)
        self.tblLivestream.setObjectName("tblLivestream")
        self.tblLivestream.setColumnCount(5)
        self.tblLivestream.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestream.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestream.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestream.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestream.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLivestream.setHorizontalHeaderItem(4, item)
        self.layoutBody.addWidget(self.tblLivestream)
        self.verticalLayout_main.addLayout(self.layoutBody)
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setSpacing(10)
        self.layoutActions.setObjectName("layoutActions")
        self.btnThem = QtWidgets.QPushButton(parent=LivestreamWidget)
        self.btnThem.setObjectName("btnThem")
        self.layoutActions.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=LivestreamWidget)
        self.btnSua.setObjectName("btnSua")
        self.layoutActions.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=LivestreamWidget)
        self.btnXoa.setObjectName("btnXoa")
        self.layoutActions.addWidget(self.btnXoa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutActions.addItem(spacerItem2)
        self.btnLuu = QtWidgets.QPushButton(parent=LivestreamWidget)
        self.btnLuu.setObjectName("btnLuu")
        self.layoutActions.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=LivestreamWidget)
        self.btnHuy.setObjectName("btnHuy")
        self.layoutActions.addWidget(self.btnHuy)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=LivestreamWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutActions)
        self.lblStatus = QtWidgets.QLabel(parent=LivestreamWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(LivestreamWidget)
        QtCore.QMetaObject.connectSlotsByName(LivestreamWidget)

    def retranslateUi(self, LivestreamWidget):
        _translate = QtCore.QCoreApplication.translate
        LivestreamWidget.setWindowTitle(_translate("LivestreamWidget", "Quản lý Livestream"))
        self.lblIconBadge.setText(_translate("LivestreamWidget", "🎥"))
        self.lblTitle.setText(_translate("LivestreamWidget", "QUẢN LÝ LIVESTREAM BÁN HÀNG"))
        self.lblSubtitle.setText(_translate("LivestreamWidget", "Quản lý lịch phát và trạng thái các buổi livestream bán hàng trực tuyến"))
        self.txtSearch.setPlaceholderText(_translate("LivestreamWidget", "Tìm kiếm livestream..."))
        self.btnSearch.setText(_translate("LivestreamWidget", "🔍 Tìm kiếm"))
        self.btnRefresh.setText(_translate("LivestreamWidget", "🔄 Làm mới"))
        self.grpLivestreamForm.setTitle(_translate("LivestreamWidget", "Thông tin Livestream"))
        self.lblTieuDe.setText(_translate("LivestreamWidget", "Tiêu đề Livestream:"))
        self.lblNguoiBan.setText(_translate("LivestreamWidget", "Người bán (Seller):"))
        self.lblNgayKhaiMac.setText(_translate("LivestreamWidget", "Thời gian bắt đầu:"))
        self.lblTrangThai.setText(_translate("LivestreamWidget", "Trạng thái thuyết trình:"))
        self.cbTrangThai.setItemText(0, _translate("LivestreamWidget", "Đang diễn ra"))
        self.cbTrangThai.setItemText(1, _translate("LivestreamWidget", "Sắp diễn ra"))
        self.cbTrangThai.setItemText(2, _translate("LivestreamWidget", "Đã kết thúc"))
        item = self.tblLivestream.horizontalHeaderItem(0)
        item.setText(_translate("LivestreamWidget", "Mã Stream"))
        item = self.tblLivestream.horizontalHeaderItem(1)
        item.setText(_translate("LivestreamWidget", "Tiêu Đề Livestream"))
        item = self.tblLivestream.horizontalHeaderItem(2)
        item.setText(_translate("LivestreamWidget", "Thời Gian Bắt Đầu"))
        item = self.tblLivestream.horizontalHeaderItem(3)
        item.setText(_translate("LivestreamWidget", "Người Bán"))
        item = self.tblLivestream.horizontalHeaderItem(4)
        item.setText(_translate("LivestreamWidget", "Trạng Thái"))
        self.btnThem.setText(_translate("LivestreamWidget", "➕ Thêm mới"))
        self.btnSua.setText(_translate("LivestreamWidget", "✏️ Sửa đổi"))
        self.btnXoa.setText(_translate("LivestreamWidget", "🗑️ Xóa bỏ"))
        self.btnLuu.setText(_translate("LivestreamWidget", "💾 Lưu lại"))
        self.btnHuy.setText(_translate("LivestreamWidget", "❌ Hủy bỏ"))
        self.btnXuatExcel.setText(_translate("LivestreamWidget", "📥 Xuất Excel"))
        self.lblStatus.setText(_translate("LivestreamWidget", "Trạng thái: Sẵn sàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LivestreamWidget = QtWidgets.QWidget()
    ui = Ui_LivestreamWidget()
    ui.setupUi(LivestreamWidget)
    LivestreamWidget.show()
    sys.exit(app.exec())
