# Form implementation generated from reading ui file 'OrderDetail.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OrderDetailWidget(object):
    def setupUi(self, OrderDetailWidget):
        OrderDetailWidget.setObjectName("OrderDetailWidget")
        OrderDetailWidget.resize(900, 600)
        OrderDetailWidget.setStyleSheet("\n"
"    QWidget {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #f5f3ff, stop:0.5 #fdf4ff, stop:1 #fff7ed);\n"
"        font-family: \"Segoe UI\";\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        color: #7c3aed;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        color: #64748b;\n"
"        font-size: 12px;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        color: #1e293b;\n"
"        border: 1px solid #e9d5ff;\n"
"        border-radius: 8px;\n"
"        margin-top: 12px;\n"
"        padding-top: 15px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        subcontrol-position: top left;\n"
"        left: 15px;\n"
"        padding: 0 5px;\n"
"    }\n"
"    QLineEdit, QComboBox, QSpinBox {\n"
"        border: 1px solid #cbd5e1;\n"
"        border-radius: 6px;\n"
"        padding: 8px 10px;\n"
"        font-size: 13px;\n"
"        color: #334155;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus, QSpinBox:focus {\n"
"        border: 2px solid #a855f7;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 6px;\n"
"        font-weight: 500;\n"
"        font-size: 13px;\n"
"        padding: 8px 15px;\n"
"        height: 34px;\n"
"    }\n"
"    QPushButton#btnSearch, QPushButton#btnLuu {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSearch:hover, QPushButton#btnLuu:hover {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6d28d9, stop:1 #db2777);\n"
"    }\n"
"    QPushButton#btnThem {\n"
"        background-color: #10b981;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnThem:hover {\n"
"        background-color: #059669;\n"
"    }\n"
"    QPushButton#btnSua {\n"
"        background-color: #f59e0b;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnSua:hover {\n"
"        background-color: #d97706;\n"
"    }\n"
"    QPushButton#btnXoa {\n"
"        background-color: #ef4444;\n"
"        color: #ffffff;\n"
"        border: none;\n"
"    }\n"
"    QPushButton#btnXoa:hover {\n"
"        background-color: #dc2626;\n"
"    }\n"
"    QPushButton#btnRefresh, QPushButton#btnHuy, QPushButton#btnXuatExcel {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #cbd5e1;\n"
"        color: #475569;\n"
"    }\n"
"    QPushButton#btnRefresh:hover, QPushButton#btnHuy:hover, QPushButton#btnXuatExcel:hover {\n"
"        background-color: #f1f5f9;\n"
"        color: #1e293b;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #e2e8f0;\n"
"        border-radius: 8px;\n"
"        gridline-color: #f1f5f9;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #ec4899);\n"
"        color: #ffffff;\n"
"        font-weight: bold;\n"
"        font-size: 12px;\n"
"        border: none;\n"
"        padding: 8px;\n"
"    }\n"
"    QTableWidget::item:selected {\n"
"        background-color: #f3e8ff;\n"
"        color: #7c3aed;\n"
"    }\n"
"   ")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(OrderDetailWidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.layoutHeader = QtWidgets.QHBoxLayout()
        self.layoutHeader.setObjectName("layoutHeader")
        self.lblIconBadge = QtWidgets.QLabel(parent=OrderDetailWidget)
        self.lblIconBadge.setMinimumSize(QtCore.QSize(44, 44))
        self.lblIconBadge.setMaximumSize(QtCore.QSize(44, 44))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblIconBadge.setFont(font)
        self.lblIconBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblIconBadge.setStyleSheet("\n"
"         #lblIconBadge {\n"
"             background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #a855f7, stop:1 #ec4899);\n"
"             border-radius: 22px;\n"
"             color: #ffffff;\n"
"         }\n"
"        ")
        self.lblIconBadge.setObjectName("lblIconBadge")
        self.layoutHeader.addWidget(self.lblIconBadge)
        self.verticalLayout_title = QtWidgets.QVBoxLayout()
        self.verticalLayout_title.setSpacing(2)
        self.verticalLayout_title.setObjectName("verticalLayout_title")
        self.lblTitle = QtWidgets.QLabel(parent=OrderDetailWidget)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_title.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=OrderDetailWidget)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_title.addWidget(self.lblSubtitle)
        self.layoutHeader.addLayout(self.verticalLayout_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutHeader.addItem(spacerItem)
        self.layoutSearch = QtWidgets.QHBoxLayout()
        self.layoutSearch.setSpacing(6)
        self.layoutSearch.setObjectName("layoutSearch")
        self.txtSearch = QtWidgets.QLineEdit(parent=OrderDetailWidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.layoutSearch.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=OrderDetailWidget)
        self.btnSearch.setObjectName("btnSearch")
        self.layoutSearch.addWidget(self.btnSearch)
        self.btnRefresh = QtWidgets.QPushButton(parent=OrderDetailWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.layoutSearch.addWidget(self.btnRefresh)
        self.layoutHeader.addLayout(self.layoutSearch)
        self.verticalLayout_main.addLayout(self.layoutHeader)
        self.layoutBody = QtWidgets.QHBoxLayout()
        self.layoutBody.setSpacing(15)
        self.layoutBody.setObjectName("layoutBody")
        self.grpOrderDetailForm = QtWidgets.QGroupBox(parent=OrderDetailWidget)
        self.grpOrderDetailForm.setMinimumSize(QtCore.QSize(320, 0))
        self.grpOrderDetailForm.setMaximumSize(QtCore.QSize(350, 16777215))
        self.grpOrderDetailForm.setObjectName("grpOrderDetailForm")
        self.verticalLayout_form = QtWidgets.QVBoxLayout(self.grpOrderDetailForm)
        self.verticalLayout_form.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_form.setSpacing(12)
        self.verticalLayout_form.setObjectName("verticalLayout_form")
        self.verticalLayout_order = QtWidgets.QVBoxLayout()
        self.verticalLayout_order.setSpacing(4)
        self.verticalLayout_order.setObjectName("verticalLayout_order")
        self.lblDonHang = QtWidgets.QLabel(parent=self.grpOrderDetailForm)
        self.lblDonHang.setObjectName("lblDonHang")
        self.verticalLayout_order.addWidget(self.lblDonHang)
        self.cbDonHang = QtWidgets.QComboBox(parent=self.grpOrderDetailForm)
        self.cbDonHang.setObjectName("cbDonHang")
        self.verticalLayout_order.addWidget(self.cbDonHang)
        self.verticalLayout_form.addLayout(self.verticalLayout_order)
        self.verticalLayout_product = QtWidgets.QVBoxLayout()
        self.verticalLayout_product.setSpacing(4)
        self.verticalLayout_product.setObjectName("verticalLayout_product")
        self.lblSanPham = QtWidgets.QLabel(parent=self.grpOrderDetailForm)
        self.lblSanPham.setObjectName("lblSanPham")
        self.verticalLayout_product.addWidget(self.lblSanPham)
        self.cbSanPham = QtWidgets.QComboBox(parent=self.grpOrderDetailForm)
        self.cbSanPham.setObjectName("cbSanPham")
        self.verticalLayout_product.addWidget(self.cbSanPham)
        self.verticalLayout_form.addLayout(self.verticalLayout_product)
        self.verticalLayout_qty = QtWidgets.QVBoxLayout()
        self.verticalLayout_qty.setSpacing(4)
        self.verticalLayout_qty.setObjectName("verticalLayout_qty")
        self.lblSoLuong = QtWidgets.QLabel(parent=self.grpOrderDetailForm)
        self.lblSoLuong.setObjectName("lblSoLuong")
        self.verticalLayout_qty.addWidget(self.lblSoLuong)
        self.spinSoLuong = QtWidgets.QSpinBox(parent=self.grpOrderDetailForm)
        self.spinSoLuong.setMaximum(9999)
        self.spinSoLuong.setProperty("value", 1)
        self.spinSoLuong.setObjectName("spinSoLuong")
        self.verticalLayout_qty.addWidget(self.spinSoLuong)
        self.verticalLayout_form.addLayout(self.verticalLayout_qty)
        self.verticalLayout_price = QtWidgets.QVBoxLayout()
        self.verticalLayout_price.setSpacing(4)
        self.verticalLayout_price.setObjectName("verticalLayout_price")
        self.lblGiaBan = QtWidgets.QLabel(parent=self.grpOrderDetailForm)
        self.lblGiaBan.setObjectName("lblGiaBan")
        self.verticalLayout_price.addWidget(self.lblGiaBan)
        self.txtGiaBan = QtWidgets.QLineEdit(parent=self.grpOrderDetailForm)
        self.txtGiaBan.setObjectName("txtGiaBan")
        self.verticalLayout_price.addWidget(self.txtGiaBan)
        self.verticalLayout_form.addLayout(self.verticalLayout_price)
        self.verticalLayout_subtotal = QtWidgets.QVBoxLayout()
        self.verticalLayout_subtotal.setSpacing(4)
        self.verticalLayout_subtotal.setObjectName("verticalLayout_subtotal")
        self.lblThanhTien = QtWidgets.QLabel(parent=self.grpOrderDetailForm)
        self.lblThanhTien.setObjectName("lblThanhTien")
        self.verticalLayout_subtotal.addWidget(self.lblThanhTien)
        self.txtThanhTien = QtWidgets.QLineEdit(parent=self.grpOrderDetailForm)
        self.txtThanhTien.setReadOnly(True)
        self.txtThanhTien.setObjectName("txtThanhTien")
        self.verticalLayout_subtotal.addWidget(self.txtThanhTien)
        self.verticalLayout_form.addLayout(self.verticalLayout_subtotal)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_form.addItem(spacerItem1)
        self.layoutBody.addWidget(self.grpOrderDetailForm)
        self.tblOrderDetail = QtWidgets.QTableWidget(parent=OrderDetailWidget)
        self.tblOrderDetail.setObjectName("tblOrderDetail")
        self.tblOrderDetail.setColumnCount(7)
        self.tblOrderDetail.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrderDetail.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrderDetail.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrderDetail.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrderDetail.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrderDetail.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrderDetail.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOrderDetail.setHorizontalHeaderItem(6, item)
        self.layoutBody.addWidget(self.tblOrderDetail)
        self.verticalLayout_main.addLayout(self.layoutBody)
        self.layoutActions = QtWidgets.QHBoxLayout()
        self.layoutActions.setSpacing(10)
        self.layoutActions.setObjectName("layoutActions")
        self.btnThem = QtWidgets.QPushButton(parent=OrderDetailWidget)
        self.btnThem.setObjectName("btnThem")
        self.layoutActions.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=OrderDetailWidget)
        self.btnSua.setObjectName("btnSua")
        self.layoutActions.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=OrderDetailWidget)
        self.btnXoa.setObjectName("btnXoa")
        self.layoutActions.addWidget(self.btnXoa)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutActions.addItem(spacerItem2)
        self.btnLuu = QtWidgets.QPushButton(parent=OrderDetailWidget)
        self.btnLuu.setObjectName("btnLuu")
        self.layoutActions.addWidget(self.btnLuu)
        self.btnHuy = QtWidgets.QPushButton(parent=OrderDetailWidget)
        self.btnHuy.setObjectName("btnHuy")
        self.layoutActions.addWidget(self.btnHuy)
        self.btnXuatExcel = QtWidgets.QPushButton(parent=OrderDetailWidget)
        self.btnXuatExcel.setObjectName("btnXuatExcel")
        self.layoutActions.addWidget(self.btnXuatExcel)
        self.verticalLayout_main.addLayout(self.layoutActions)
        self.lblStatus = QtWidgets.QLabel(parent=OrderDetailWidget)
        self.lblStatus.setStyleSheet("color: #64748b; font-size: 11px; font-weight: 500;")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_main.addWidget(self.lblStatus)

        self.retranslateUi(OrderDetailWidget)
        QtCore.QMetaObject.connectSlotsByName(OrderDetailWidget)

    def retranslateUi(self, OrderDetailWidget):
        _translate = QtCore.QCoreApplication.translate
        OrderDetailWidget.setWindowTitle(_translate("OrderDetailWidget", "Chi tiết Đơn hàng"))
        self.lblIconBadge.setText(_translate("OrderDetailWidget", "📝"))
        self.lblTitle.setText(_translate("OrderDetailWidget", "CHI TIẾT ĐƠN HÀNG (ORDER DETAIL LIST)"))
        self.lblSubtitle.setText(_translate("OrderDetailWidget", "Liên kết thông tin chi tiết sản phẩm bán ra cùng số lượng và giá bán thực tế trong từng đơn hàng"))
        self.txtSearch.setPlaceholderText(_translate("OrderDetailWidget", "Tìm theo mã đơn hàng, sản phẩm..."))
        self.btnSearch.setText(_translate("OrderDetailWidget", "🔍 Tìm kiếm"))
        self.btnRefresh.setText(_translate("OrderDetailWidget", "🔄 Làm mới"))
        self.grpOrderDetailForm.setTitle(_translate("OrderDetailWidget", "Thông tin sản phẩm bán ra"))
        self.lblDonHang.setText(_translate("OrderDetailWidget", "Đơn Hàng:"))
        self.lblSanPham.setText(_translate("OrderDetailWidget", "Sản phẩm:"))
        self.lblSoLuong.setText(_translate("OrderDetailWidget", "Số lượng mua:"))
        self.lblGiaBan.setText(_translate("OrderDetailWidget", "Giá bán thực tế (VND):"))
        self.lblThanhTien.setText(_translate("OrderDetailWidget", "Thành tiền (VND):"))
        self.txtThanhTien.setText(_translate("OrderDetailWidget", "0"))
        item = self.tblOrderDetail.horizontalHeaderItem(0)
        item.setText(_translate("OrderDetailWidget", "Mã Chi Tiết ĐH"))
        item = self.tblOrderDetail.horizontalHeaderItem(1)
        item.setText(_translate("OrderDetailWidget", "Đơn Hàng"))
        item = self.tblOrderDetail.horizontalHeaderItem(2)
        item.setText(_translate("OrderDetailWidget", "Mã Sản Phẩm"))
        item = self.tblOrderDetail.horizontalHeaderItem(3)
        item.setText(_translate("OrderDetailWidget", "Tên Sản Phẩm"))
        item = self.tblOrderDetail.horizontalHeaderItem(4)
        item.setText(_translate("OrderDetailWidget", "SL Mua"))
        item = self.tblOrderDetail.horizontalHeaderItem(5)
        item.setText(_translate("OrderDetailWidget", "Đơn Giá Bán"))
        item = self.tblOrderDetail.horizontalHeaderItem(6)
        item.setText(_translate("OrderDetailWidget", "Thành Tiền (VND)"))
        self.btnThem.setText(_translate("OrderDetailWidget", "➕ Thêm mới"))
        self.btnSua.setText(_translate("OrderDetailWidget", "✏️ Sửa đổi"))
        self.btnXoa.setText(_translate("OrderDetailWidget", "🗑️ Xóa bỏ"))
        self.btnLuu.setText(_translate("OrderDetailWidget", "💾 Lưu lại"))
        self.btnHuy.setText(_translate("OrderDetailWidget", "❌ Hủy bỏ"))
        self.btnXuatExcel.setText(_translate("OrderDetailWidget", "📥 Xuất Excel"))
        self.lblStatus.setText(_translate("OrderDetailWidget", "Trạng thái: Sẵn sàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrderDetailWidget = QtWidgets.QWidget()
    ui = Ui_OrderDetailWidget()
    ui.setupUi(OrderDetailWidget)
    OrderDetailWidget.show()
    sys.exit(app.exec())
